// AYLuaCodegen.cpp - AST → Lua source generator (S2.5)
//
// S2.5 redesign: `component` → `script`, `export var` removed. All `var`
// declarations become `local` Lua variables. `self` is the canonical way
// to access the bound ScriptComponent; field access is left as bare Lua
// member syntax (`self.field`) for now — S3 will route it through
// AYReflect-backed accessors.

#include "logia/AYLuaCodegen.h"

#include <cstdio>
#include <sstream>
#include <utility>

namespace ayt::script::logia
{

namespace {

const char* tokenOpName(TokenType t)
{
    switch (t) {
    case TokenType::Plus:       return "+";
    case TokenType::Minus:      return "-";
    case TokenType::Star:       return "*";
    case TokenType::Slash:      return "/";
    case TokenType::Percent:    return "%";
    case TokenType::Equal:      return "=";
    case TokenType::PlusEqual:  return "+=";
    case TokenType::MinusEqual: return "-=";
    case TokenType::StarEqual:  return "*=";
    case TokenType::SlashEqual: return "/=";
    case TokenType::EqualEqual: return "==";
    case TokenType::BangEqual:  return "~=";
    case TokenType::Less:       return "<";
    case TokenType::LessEqual:  return "<=";
    case TokenType::Greater:    return ">";
    case TokenType::GreaterEqual: return ">=";
    case TokenType::And:        return "and";
    case TokenType::Or:         return "or";
    default: return "?";
    }
}

} // namespace

LuaCodegen::LuaCodegen(LuaCodegenOptions options)
    : _options(std::move(options)) {}

LuaCodegenResult LuaCodegen::generate(const Program& program)
{
    LuaCodegenResult result;
    _errors.clear();
    _out.clear();
    _indent = 0;
    _tmpCounter = 0;

    _out += "-- Auto-generated by AYLuaCodegen from ";
    _out += _options.scriptName.empty() ? std::string("Logia source") : _options.scriptName;
    _out += "\n";
    _out += "local M = {}\n\n";

    // S2.5: a `.logia` file produces exactly one module (one `script`
    // block). Multiple scripts in one file generate multiple modules —
    // call once per script from the loader. For now, generate only the
    // first script (the parser produces a single `ScriptDecl` per file
    // in practice; the loader can re-enter `generate` with another
    // Program if needed).
    if (program.scripts.empty()) {
        CompilerError err;
        err.code = ErrorCode::InvalidStatement;
        err.message = "Logia file contains no script declaration";
        err.line = 0;
        err.column = 0;
        _errors.push_back(err);
    } else {
        emitScript(*program.scripts[0]);
    }

    _out += "\nreturn M\n";

    result.errors = _errors;
    result.source = _out;
    result.success = _errors.empty();
    return result;
}

// ============================================================
// Scripts
// ============================================================

void LuaCodegen::emitScript(const ScriptDecl& script)
{
    // Var declarations first (locals). Lifecycle functions come next.
    for (const auto& member : script.members) {
        if (auto* var = dynamic_cast<VarDeclStmt*>(member.get())) {
            emitLocalVar(*var);
        }
    }

    for (const auto& member : script.members) {
        if (auto* fn = dynamic_cast<LifecycleFuncDecl*>(member.get())) {
            emitLifecycleFunc(*fn);
            _out += "\n";
        }
    }
}

void LuaCodegen::emitLocalVar(const VarDeclStmt& var)
{
    indent();
    _out += "local ";
    _out += var.name;
    _out += " = ";
    if (var.initializer) {
        _out += emitExpr(*var.initializer);
    } else {
        _out += "nil";
    }
    _out += "\n";
}

void LuaCodegen::emitLifecycleFunc(const LifecycleFuncDecl& func)
{
    indent();
    _out += "function M.";
    _out += lifecycleKindName(func.kind);
    // S2.5: lifecycle functions take no parameters. `self` is injected
    // by the runtime bridge. If the AST ever carries params (forward
    // compat for future event handlers), emit them too.
    _out += "(self";
    for (const auto& p : func.params) {
        _out += ", ";
        _out += p.name;
    }
    _out += ")\n";

    ++_indent;
    emitBlock(func.body);
    --_indent;

    indent();
    _out += "end\n";
}

// ============================================================
// Statements
// ============================================================

void LuaCodegen::emitBlock(const std::vector<StmtPtr>& body)
{
    for (const auto& stmt : body) {
        emitStmt(*stmt);
    }
}

void LuaCodegen::emitStmt(const Stmt& stmt)
{
    if (auto* v = dynamic_cast<const VarDeclStmt*>(&stmt)) { emitVarDecl(*v); return; }
    if (auto* i = dynamic_cast<const IfStmt*>(&stmt))      { emitIfStmt(*i);   return; }
    if (auto* r = dynamic_cast<const ReturnStmt*>(&stmt))  { emitReturnStmt(*r); return; }
    if (auto* e = dynamic_cast<const ExprStmt*>(&stmt))    { emitExprStmt(*e); return; }
    errorAt(Token{}, "Unsupported statement in codegen");
}

void LuaCodegen::emitVarDecl(const VarDeclStmt& var)
{
    indent();
    _out += "local ";
    _out += var.name;
    _out += " = ";
    if (var.initializer) {
        _out += emitExpr(*var.initializer);
    } else {
        _out += "nil";
    }
    _out += "\n";
}

void LuaCodegen::emitIfStmt(const IfStmt& stmt)
{
    indent();
    _out += "if ";
    _out += emitExpr(*stmt.condition);
    _out += " then\n";

    ++_indent;
    emitBlock(stmt.thenBranch);
    --_indent;

    if (!stmt.elseBranch.empty()) {
        indent();
        _out += "else\n";
        ++_indent;
        emitBlock(stmt.elseBranch);
        --_indent;
    }

    indent();
    _out += "end\n";
}

void LuaCodegen::emitReturnStmt(const ReturnStmt& stmt)
{
    indent();
    _out += "return";
    if (stmt.value) {
        _out += " ";
        _out += emitExpr(*stmt.value);
    }
    _out += "\n";
}

void LuaCodegen::emitExprStmt(const ExprStmt& stmt)
{
    if (!stmt.expr) {
        return;
    }

    if (auto* bin = dynamic_cast<BinaryExpr*>(stmt.expr.get())) {
        TokenType op = bin->op.type;
        if (op == TokenType::Equal ||
            op == TokenType::PlusEqual || op == TokenType::MinusEqual ||
            op == TokenType::StarEqual || op == TokenType::SlashEqual) {

            std::string rhs;
            if (op == TokenType::Equal) {
                rhs = emitExpr(*bin->right);
            } else {
                rhs = emitCompoundRhs(*bin->left, tokenOpName(op), *bin->right);
            }
            std::string target = emitAssignmentTarget(*bin->left);
            indent();
            _out += target;
            _out += " = ";
            _out += rhs;
            _out += "\n";
            return;
        }
    }

    indent();
    _out += emitExpr(*stmt.expr);
    _out += "\n";
}

// ============================================================
// Expressions
// ============================================================

std::string LuaCodegen::emitExpr(const Expr& expr)
{
    if (auto* b = dynamic_cast<const BinaryExpr*>(&expr)) {
        std::string l = emitExpr(*b->left);
        std::string r = emitExpr(*b->right);
        std::string out;
        out.reserve(l.size() + r.size() + 4);
        out += "(";
        out += l;
        out += " ";
        out += tokenOpName(b->op.type);
        out += " ";
        out += r;
        out += ")";
        return out;
    }
    if (auto* u = dynamic_cast<const UnaryExpr*>(&expr)) {
        std::string inner = emitExpr(*u->operand);
        std::string out;
        if (u->op.type == TokenType::Minus) {
            out += "(-";
            out += inner;
            out += ")";
        } else if (u->op.type == TokenType::Bang) {
            out += "(not ";
            out += inner;
            out += ")";
        } else {
            errorAt(u->op, "Unsupported unary operator");
            return "nil";
        }
        return out;
    }
    if (auto* c = dynamic_cast<const CallExpr*>(&expr)) {
        std::string callee = emitExpr(*c->callee);
        std::string out;
        out += callee;
        out += "(";
        bool first = true;
        for (const auto& a : c->args) {
            if (!first) out += ", ";
            out += emitExpr(*a);
            first = false;
        }
        out += ")";
        return out;
    }
    if (auto* m = dynamic_cast<const MemberExpr*>(&expr)) {
        std::string obj = emitExpr(*m->object);
        std::string out;
        out += obj;
        out += ".";
        out += m->member;
        return out;
    }
    if (auto* i = dynamic_cast<const IndexExpr*>(&expr)) {
        std::string obj = emitExpr(*i->object);
        std::string idx = emitExpr(*i->index);
        std::string out;
        out += obj;
        out += "[";
        out += idx;
        out += "]";
        return out;
    }
    if (auto* id = dynamic_cast<const IdentifierExpr*>(&expr)) {
        return id->name;
    }
    if (auto* lit = dynamic_cast<const LiteralExpr*>(&expr)) {
        if (std::holds_alternative<bool>(lit->value)) {
            return std::get<bool>(lit->value) ? "true" : "false";
        }
        if (std::holds_alternative<int>(lit->value)) {
            return std::to_string(std::get<int>(lit->value));
        }
        if (std::holds_alternative<float>(lit->value)) {
            std::ostringstream oss;
            oss << std::get<float>(lit->value);
            return oss.str();
        }
        if (std::holds_alternative<std::string>(lit->value)) {
            return escapeString(std::get<std::string>(lit->value));
        }
        return "nil";
    }
    errorAt(Token{}, "Unsupported expression in codegen");
    return "nil";
}

// ============================================================
// Compound assignment lowering
//
// `transform.position.y += jump_force * dt` lowers to:
//   local __tmp_0 = transform.position
//   __tmp_0.y = __tmp_0.y + (jump_force * dt)
//
// emitAssignmentTarget() emits the prefix-statement fragment that creates
// the temporary and returns the Lua expression to use as the LHS.
// ============================================================

namespace {

bool collectMemberChain(const Expr& e, std::vector<std::string>& members)
{
    if (auto* m = dynamic_cast<const MemberExpr*>(&e)) {
        members.push_back(m->member);
        return collectMemberChain(*m->object, members);
    }
    return !members.empty();
}

} // namespace

std::string LuaCodegen::emitAssignmentTarget(const Expr& target)
{
    std::vector<std::string> members;
    if (!collectMemberChain(target, members)) {
        return emitExpr(target);
    }
    std::vector<std::string> rev(members.rbegin(), members.rend());
    std::string tmpName = freshTmp("lhs");
    indent();
    _out += "local ";
    _out += tmpName;
    _out += " = ";
    if (auto* m = dynamic_cast<const MemberExpr*>(&target)) {
        _out += emitExpr(*m->object);
        for (size_t i = 1; i + 1 < rev.size(); ++i) {
            _out += ".";
            _out += rev[i];
        }
    } else {
        _out += "nil";
    }
    _out += "\n";

    std::string out;
    out += tmpName;
    out += ".";
    out += rev.back();
    return out;
}

std::string LuaCodegen::emitCompoundRhs(const Expr& target,
                                       const std::string& op,
                                       const Expr& rhs)
{
    std::vector<std::string> members;
    std::string lhsStr;
    if (collectMemberChain(target, members)) {
        std::vector<std::string> rev(members.rbegin(), members.rend());
        if (auto* m = dynamic_cast<const MemberExpr*>(&target)) {
            lhsStr = emitExpr(*m->object);
            for (size_t i = 1; i < rev.size(); ++i) {
                lhsStr += ".";
                lhsStr += rev[i];
            }
        }
    } else {
        lhsStr = emitExpr(target);
    }
    std::string rhsStr = emitExpr(rhs);
    std::string out;
    out += lhsStr;
    out += " ";
    out += op;
    out += " ";
    out += rhsStr;
    return out;
}

std::string LuaCodegen::freshTmp(const std::string& hint)
{
    ++_tmpCounter;
    std::string name = "__tmp_";
    if (!hint.empty()) {
        name += hint;
        name += "_";
    }
    name += std::to_string(_tmpCounter);
    return name;
}

// ============================================================
// Helpers
// ============================================================

void LuaCodegen::line(const std::string& s)
{
    indent();
    _out += s;
    _out += "\n";
}

void LuaCodegen::indent()
{
    for (int i = 0; i < _indent; ++i) _out += "    ";
}

void LuaCodegen::dedent()
{
    if (_indent > 0) --_indent;
}

std::string LuaCodegen::escapeString(const std::string& s) const
{
    std::string out;
    out.reserve(s.size() + 2);
    out += '"';
    for (char c : s) {
        switch (c) {
        case '"':  out += "\\\""; break;
        case '\\': out += "\\\\"; break;
        case '\n': out += "\\n";  break;
        case '\r': out += "\\r";  break;
        case '\t': out += "\\t";  break;
        default:
            if (static_cast<unsigned char>(c) < 0x20) {
                char buf[8];
                std::snprintf(buf, sizeof(buf), "\\x%02X", static_cast<unsigned char>(c));
                out += buf;
            } else {
                out += c;
            }
        }
    }
    out += '"';
    return out;
}

void LuaCodegen::errorAt(const Token& tok, const std::string& message)
{
    CompilerError err;
    err.code = ErrorCode::InvalidStatement;
    err.message = message;
    err.line = tok.line;
    err.column = tok.column;
    _errors.push_back(err);
}

} // namespace ayt::script::logia