// AYLuaCodegen.cpp - AST → Lua source generator (S2.5)
//
// S2.5 redesign: `component` → `script`, `export var` removed. All `var`
// declarations become `local` Lua variables. `self` is the canonical way
// to access the bound ScriptComponent; field access is left as bare Lua
// member syntax (`self.field`) for now — S3 will route it through
// AYReflect-backed accessors.

#include "AYScript/logia/LuaCodegen.h"

// LG-05 / S3.3: full ITypeInfo definition so we can call
// getFieldCount() on the resolved leaf type of `self.<field>`
// and decide between the reflect-call rewrite and the legacy
// bare-member codegen.
#include "AYReflect/IReflect.h"

#include <cstdio>
#include <sstream>
#include <utility>

namespace ayt::script::logia
{

namespace {

const char* tokenOpName(TokenType t)
{
    switch (t) {
    case TokenType::Plus:       return "+";
    case TokenType::Minus:      return "-";
    case TokenType::Star:       return "*";
    case TokenType::Slash:      return "/";
    case TokenType::Percent:    return "%";
    case TokenType::Equal:      return "=";
    case TokenType::PlusEqual:  return "+=";
    case TokenType::MinusEqual: return "-=";
    case TokenType::StarEqual:  return "*=";
    case TokenType::SlashEqual: return "/=";
    case TokenType::EqualEqual: return "==";
    case TokenType::BangEqual:  return "~=";
    case TokenType::Less:       return "<";
    case TokenType::LessEqual:  return "<=";
    case TokenType::Greater:    return ">";
    case TokenType::GreaterEqual: return ">=";
    case TokenType::And:        return "and";
    case TokenType::Or:         return "or";
    default: return "?";
    }
}

} // namespace

// R5.2-B (2026-07-14): emit `::L::` markers for each top-level
// LabelDeclStmt in `body`, at the current indent. The caller
// (emitWhileStmt / emitForStmt) invokes this AFTER writing the
// loop's `end` keyword, so the label lands at the same indent
// as the loop header — i.e. immediately AFTER the loop. This
// is what makes `break :L` work: the compiled `goto L` jumps to
// the label at loop end, falling out of the loop.
//
// We do NOT emit the label inside the loop body because Lua
// 5.2+ forbids re-declaring a label in the same block (a
// loop's body is one block across all iterations).
//
// Implementation note: the body comes in as `const
// std::vector<StmtPtr>&` (the loop's body field is read-only).
// Copying `unique_ptr` is forbidden, so we cannot build a
// "stripped body" vector — the caller walks the body twice
// (emitBlockSkipLabels iterates the body and skips labels;
// this helper iterates the body and emits only labels).
void LuaCodegen::hoistLabelsFromBody(const std::vector<StmtPtr>& body)
{
    for (const auto& s : body) {
        if (auto* ld = dynamic_cast<const LabelDeclStmt*>(s.get())) {
            // S5 ED-03 (2026-07-15): hoisted labels are anchored to
            // the enclosing loop's sourceLoc (set by emitStmt() before
            // dispatching into emitWhileStmt / emitForStmt). The label
            // sourceLoc itself is irrelevant for runtime panic
            // translation — a `goto L` that lands on a hoisted label
            // is a Logia `break :L` source line, which is the loop's
            // sourceLoc.
            std::string out;
            out += "::";
            out += ld->name;
            out += "::";
            writeLine(out);
        }
    }
}

LuaCodegen::LuaCodegen(LuaCodegenOptions options)
    : _options(std::move(options)) {}

LuaCodegenResult LuaCodegen::generate(const Program& program)
{
    LuaCodegenResult result;
    _errors.clear();
    _out.clear();
    _indent = 0;
    _tmpCounter = 0;

    // S5 ED-03 (2026-07-15): preamble is codegen-internal (no Logia
    // source anchor). writeNoAnchor tracks the line count for the
    // source map without recording a user-anchored Logia loc — a
    // runtime panic on these lines is structurally a codegen bug.
    std::string headerComment = "-- Auto-generated by AYLuaCodegen from ";
    headerComment += _options.scriptName.empty() ? std::string("Logia source") : _options.scriptName;
    writeNoAnchor(headerComment);
    writeNoAnchor("local M = {}");
    writeBlankLine();

    // S2.5: a `.logia` file produces exactly one module (one `script`
    // block). Multiple scripts in one file generate multiple modules —
    // call once per script from the loader. For now, generate only the
    // first script (the parser produces a single `ScriptDecl` per file
    // in practice; the loader can re-enter `generate` with another
    // Program if needed).
    if (program.scripts.empty()) {
        CompilerError err;
        err.code = ErrorCode::InvalidStatement;
        err.message = "Logia file contains no script declaration";
        err.line = 0;
        err.column = 0;
        _errors.push_back(err);
    } else {
        emitScript(*program.scripts[0]);
    }

    // S5 ED-03 (2026-07-15): epilogue is also codegen-internal. Use
    // the same writeNoAnchor + writeBlankLine pair as the preamble
    // so the bridge treats these lines as untranslatable.
    writeBlankLine();
    writeNoAnchor("return M");

    result.errors = _errors;
    result.source = _out;
    // S5 ED-03 (2026-07-15): per-line Lua → Logia source map. The
    // header (`local M = {}` on Lua line 1) and footer (`return M`
    // on the last line) are NOT anchored — they have no Logia
    // source location (codegen preamble/epilogue). Their
    // corresponding entries in `_sourceMap.luaLineToSource` are
    // default-constructed SourceLocation with `line == 0`, which
    // the bridge's translation treats as "untranslatable" (no
    // source-mapped Logia line). A runtime panic on those lines is
    // a codegen bug, not a user-source bug, so untranslatable is
    // the correct behavior.
    result.sourceMap = _sourceMap;
    result.success = _errors.empty();
    return result;
}

// ============================================================
// Scripts
// ============================================================

void LuaCodegen::emitScript(const ScriptDecl& script)
{
    // LG-05 / S3.3: record the host type name for `self.<field>`
    // reflect-call rewrites. Scope is per-script — reset on exit.
    _currentHostTypeName = script.hostTypeName;

    // S4.1 (2026-07-15): zero-cost guard. If the script declares
    // no signals, we emit no helper block — `__ay_emit` / `__ay_connect`
    // / `_signalNames` are pure overhead for scripts that don't use
    // the surface. Cache the decision up-front so the per-pass
    // loops below don't have to recompute it.
    bool hasAnySignal = false;
    for (const auto& member : script.members) {
        if (dynamic_cast<SignalDeclStmt*>(member.get())) {
            hasAnySignal = true;
            break;
        }
    }

    // S4.1 (2026-07-15): when signals exist, emit the helper block
    // once per module BEFORE any function body. The block:
    //   1. records `M._signalNames = { ["name1"] = true, ... }`
    //      for tooling / debug / hot-reload introspection. Runtime
    //      codegen does NOT read this — validation is compile-time.
    //   2. defines `__ay_connect` / `__ay_emit` against
    //      `M._instanceSignals[self]` — NOT `self._signals`.
    //      Logia `self` is a lightuserdata (C++ host pointer); Lua
    //      cannot index lightuserdata. Key the module table by the
    //      lightuserdata itself so each receiver stays isolated.
    // Anchor to the FIRST signal decl's sourceLoc so runtime panic
    // translation (S5 ED-03) points at the signal keyword if a
    // helper raises.
    if (hasAnySignal) {
        const SignalDeclStmt* firstSignal = nullptr;
        for (const auto& member : script.members) {
            if (auto* s = dynamic_cast<SignalDeclStmt*>(member.get())) {
                firstSignal = s;
                break;
            }
        }
        if (firstSignal) _currentAnchor = firstSignal->sourceLoc;

        // Build `M._signalNames = { ["a"] = true, ["b"] = true }`.
        // Single-line emit keeps the source map dense. Whitespace
        // around `{` matches the S4.1 acceptance test's strict
        // substring check (`containsFlat` is exact-match, not
        // whitespace-tolerant).
        std::string namesLine = "M._signalNames = { ";
        bool firstName = true;
        for (const auto& member : script.members) {
            if (auto* s = dynamic_cast<const SignalDeclStmt*>(member.get())) {
                if (!firstName) namesLine += ", ";
                namesLine += "[\"";
                namesLine += s->name;
                namesLine += "\"] = true";
                firstName = false;
            }
        }
        namesLine += " }";
        writeLine(namesLine);

        writeLine("M._instanceSignals = M._instanceSignals or {}");
        // D-2: module-local slot bound for the duration of handler
        // dispatch. Script-block helpers are top-level Lua functions
        // (no `self` parameter); they read this slot when the
        // Logia source mentions `self`. Connect-wrap upvalues alone
        // cannot inject into a separately defined helper's scope.
        writeLine("local __ay_bound_self = nil");
        // The three helpers — emitted as separate lines so each is
        // anchored to the signal keyword (any helper panic still
        // maps back to the signal line). S4.1b (2026-07-18) added
        // `__ay_disconnect` and reshaped `__ay_connect` /
        // `__ay_emit` to track per-record `dead` tombstones + a
        // bag-scoped `_nextId` counter so connect can return an
        // int connection id that disconnect uses to deregister.
        //
        // Dense-mark tombstone (D-4): disconnect sets `rec.dead =
        // true` rather than `list[i] = nil` because Lua's
        // `ipairs()` stops at the first nil (Lua 5.4 reference
        // manual §6.1 — "stops at first absent index"). Slot is
        // kept in place; emit skips via `if not rec.dead`. O(1)
        // disconnect, full sweep on emit.
        writeLine("local function __ay_connect(self, name, handler)");
        writeLine("    local bag = M._instanceSignals[self]");
        writeLine("    if not bag then bag = {}; M._instanceSignals[self] = bag end");
        writeLine("    local id = bag._nextId or 1");
        writeLine("    bag._nextId = id + 1");
        writeLine("    local list = bag[name]");
        writeLine("    if not list then list = {}; bag[name] = list end");
        writeLine("    list[#list + 1] = { id = id, fn = handler }");
        writeLine("    return id");
        writeLine("end");
        writeBlankLine();
        writeLine("local function __ay_disconnect(self, id)");
        writeLine("    local bag = M._instanceSignals[self]");
        writeLine("    if not bag then return end");
        writeLine("    for name, list in pairs(bag) do");
        writeLine("        if type(list) == \"table\" then");
        writeLine("            for i, rec in ipairs(list) do");
        writeLine("                if rec.id == id then");
        writeLine("                    rec.dead = true");
        writeLine("                    return");
        writeLine("                end");
        writeLine("            end");
        writeLine("        end");
        writeLine("    end");
        writeLine("end");
        writeBlankLine();
        writeLine("local function __ay_emit(self, name, ...)");
        writeLine("    local bag = M._instanceSignals[self]; if not bag then return end");
        writeLine("    local list = bag[name]; if not list then return end");
        writeLine("    local prev = __ay_bound_self");
        writeLine("    __ay_bound_self = self");
        writeLine("    for i, rec in ipairs(list) do");
        writeLine("        if not rec.dead then rec.fn(...) end");
        writeLine("    end");
        writeLine("    __ay_bound_self = prev");
        writeLine("end");
        writeBlankLine();
    }

    // S5 ED-03 (2026-07-15): each top-level member is anchored to
    // its own sourceLoc before emit. The `emitStmt` dispatcher
    // handles nested Stmts; this top-level loop is the
    // `emitScript`-level dispatcher for `ScriptDecl::members` and
    // must mirror the anchor-update behavior to keep
    // `_currentAnchor` in sync with the active Stmt's source
    // location.
    // Var declarations first (locals). Lifecycle functions come next.
    for (const auto& member : script.members) {
        if (auto* var = dynamic_cast<VarDeclStmt*>(member.get())) {
            _currentAnchor = member->sourceLoc;
            emitLocalVar(*var);
        }
    }

    for (const auto& member : script.members) {
        if (auto* fn = dynamic_cast<LifecycleFuncDecl*>(member.get())) {
            _currentAnchor = member->sourceLoc;
            emitLifecycleFunc(*fn);
            // S5 ED-03 (2026-07-15): blank line between functions for
            // readability; anchored to {} (no Logia source).
            writeBlankLine();
        }
    }

    // 2026-07-11 audit fix: user-defined script-block-scope helpers.
    // Emitted after lifecycles so they're hoisted before the first
    // `M.on_start(...)` reference (Lua hoists top-level function
    // statements anyway, but ordering improves readability). Lifecycle
    // bodies call them via bare name (`doubleIt(21)`), and the bare
    // name resolves to the top-level `function doubleIt(...) ... end`
    // we emit here.
    for (const auto& member : script.members) {
        if (auto* fn = dynamic_cast<const FunctionDeclStmt*>(member.get())) {
            _currentAnchor = member->sourceLoc;
            emitFunctionDecl(*fn);
            // S5 ED-03 (2026-07-15): same blank-line readability
            // treatment as the lifecycle loop above.
            writeBlankLine();
        }
    }
}

void LuaCodegen::emitLocalVar(const VarDeclStmt& var)
{
    // S5 ED-03 (2026-07-15): collapse the multi-write pattern into
    // a single writeLine() so the anchor is recorded exactly once
    // for this VarDeclStmt's line.
    std::string line;
    line += "local ";
    line += var.name;
    line += " = ";
    if (var.initializer) {
        line += emitExpr(*var.initializer);
    } else {
        line += "nil";
    }
    writeLine(line);
}

void LuaCodegen::emitLifecycleFunc(const LifecycleFuncDecl& func)
{
    // S5 ED-03 (2026-07-15): the function header is one Lua line
    // ("function M.on_X(self[, params])") — collapse to one
    // writeLine. The body block and trailing `end` are emitted via
    // separate emit paths that each call writeLine themselves.
    std::string header;
    header += "function M.";
    header += lifecycleKindName(func.kind);
    // S3.8b: when the host context's `expectSelf` is false (Tool
    // host), emit a parameter list with NO `self`. The ToolRunner
    // passes `receiver = nullptr` at call time — emitting `self`
    // here would mismatch Lua's call arity (`function M.run(self)`
    // expects one arg, the bridge calls with zero).
    //
    // Component / System / EventHandler hosts keep the S2.5 shape
    // `function M.on_*(self[, ...legacyParams])`. Legacy params from
    // the parser are still forwarded for forward-compat with future
    // event-handler signatures (e.g. `on_damage(amount: float)`).
    const bool emitSelf = _options.hostContext.expectSelf;
    if (emitSelf) {
        header += "(self";
        for (const auto& p : func.params) {
            header += ", ";
            header += p.name;
        }
        header += ")";
    } else {
        // No self. Legacy params still go through (the parser only
        // emits them as a documentation affordance, but codegen is
        // the single source of truth — forwarding them keeps the
        // signature shape stable if a future event handler is bound
        // through the same plumbing with expectSelf re-enabled).
        if (func.params.empty()) {
            header += "()";
        } else {
            header += "(";
            bool first = true;
            for (const auto& p : func.params) {
                if (!first) header += ", ";
                header += p.name;
                first = false;
            }
            header += ")";
        }
    }
    writeLine(header);

    ++_indent;
    emitBlock(func.body);
    --_indent;

    writeLine("end");
}

// ============================================================
// Statements
// ============================================================

void LuaCodegen::emitBlock(const std::vector<StmtPtr>& body)
{
    for (const auto& stmt : body) {
        emitStmt(*stmt);
    }
}

// R5.2-B (2026-07-14): like emitBlock, but skips top-level
// LabelDeclStmt nodes. Used by emitWhileStmt / emitForStmt to
// avoid re-emitting labels that have already been hoisted to
// immediately before the loop's `for` / `while` header (Lua
// 5.2+ forbids re-declaring a label in the same block, and a
// loop body is one block across all iterations).
//
// Nested labels (LabelDeclStmt inside an `if` / `do` / nested
// loop) are NOT skipped here — they reach emitStmt via
// emitBlock and are emitted verbatim. Hoisting applies only
// to direct-child labels of the immediate loop body.
void LuaCodegen::emitBlockSkipLabels(const std::vector<StmtPtr>& body)
{
    for (const auto& stmt : body) {
        if (dynamic_cast<const LabelDeclStmt*>(stmt.get())) continue;
        emitStmt(*stmt);
    }
}

// 2026-07-11 audit fix: emit a top-level Lua function for a
// script-block-scope helper. Mirrors `emitLifecycleFunc`'s shape but
// without the `M.` prefix — the function is reachable from every
// lifecycle body in the same module via its bare name.
void LuaCodegen::emitFunctionDecl(const FunctionDeclStmt& fn)
{
    // S5 ED-03 (2026-07-15): single writeLine for the header
    // (matches emitLifecycleFunc's shape — anchor recorded once).
    std::string header;
    header += "function ";
    header += fn.name;
    header += "(";
    for (size_t i = 0; i < fn.params.size(); ++i) {
        if (i > 0) header += ", ";
        header += fn.params[i].name;
    }
    header += ")";
    writeLine(header);
    ++_indent;
    // S4.1 D-2: rewrite bare `self` inside helpers to `__ay_bound_self`
    // (set by `__ay_emit` around handler dispatch).
    const bool prevHelper = _emittingScriptHelper;
    _emittingScriptHelper = true;
    for (const auto& s : fn.body) {
        emitStmt(*s);
    }
    _emittingScriptHelper = prevHelper;
    --_indent;
    writeLine("end");
}

void LuaCodegen::emitStmt(const Stmt& stmt)
{
    // S5 ED-03 (2026-07-15): anchor every emitStmt call to the
    // current Stmt's `sourceLoc` so subsequent writeLine() calls
    // record this Stmt's Logia line as the anchor for any Lua
    // line(s) emitted. emitStmt is the single dispatcher for all
    // 13 Stmt subclasses; setting the anchor here covers every
    // emit path uniformly.
    _currentAnchor = stmt.sourceLoc;

    if (auto* v = dynamic_cast<const VarDeclStmt*>(&stmt)) { emitVarDecl(*v); return; }
    if (auto* i = dynamic_cast<const IfStmt*>(&stmt))      { emitIfStmt(*i);   return; }
    // R5.0 (2026-07-13): loop statements. WhileStmt and ForStmt
    // dispatch BEFORE ReturnStmt so a `return` inside a loop body
    // (R5.0.1) would be parsed/handled by parseWhileStmt / parseForStmt
    // itself — no interference here.
    if (auto* w = dynamic_cast<const WhileStmt*>(&stmt))   { emitWhileStmt(*w); return; }
    if (auto* f = dynamic_cast<const ForStmt*>(&stmt))     { emitForStmt(*f);   return; }
    // R5.1 (2026-07-13): break / continue. Lua 5.5 supports both
    // natively (Lua 5.2+ added `continue`). Codegen emits them
    // verbatim — the parser's loopDepth gate has already verified
    // these appear inside a loop body, so the emitted Lua is also
    // guaranteed to be in a valid context.
    if (auto* b = dynamic_cast<const BreakStmt*>(&stmt))    { emitBreakStmt(*b); return; }
    if (auto* c = dynamic_cast<const ContinueStmt*>(&stmt)) { emitContinueStmt(*c); return; }
    // R5.2-A (2026-07-13): block-scope statement. Lowered to Lua
    // 5.2+ native `do ... end`. The Logia-side `do` / `end` /
    // braces in source are consumed by the parser; this emit
    // produces the shell only.
    if (auto* blk = dynamic_cast<const BlockStmt*>(&stmt))   { emitBlockStmt(*blk); return; }
    // R5.2-B (2026-07-14): label declaration. Lowered to Lua
    // 5.2+ `::NAME::` natively. Codegen only writes the marker.
    if (auto* lbl = dynamic_cast<const LabelDeclStmt*>(&stmt)) { emitLabelDeclStmt(*lbl); return; }
    if (auto* r = dynamic_cast<const ReturnStmt*>(&stmt))  { emitReturnStmt(*r); return; }
    if (auto* e = dynamic_cast<const ExprStmt*>(&stmt))    { emitExprStmt(*e); return; }
    // 2026-07-11 audit fix: defensive — parser rejects `function`
    // inside lifecycle bodies, but if codegen ever sees one here
    // (e.g. via a malformed AST forged by a hostile serializer)
    // we still emit clean Lua rather than corrupting the chunk.
    if (auto* fn = dynamic_cast<const FunctionDeclStmt*>(&stmt)) {
        emitFunctionDecl(*fn);
        return;
    }
    // S4.1 (2026-07-15): defensive — SignalDeclStmt's runtime
    // surface is the helper block + `M._signalNames` metadata
    // emitted by `emitScript` (which runs before any member loop).
    // The per-member loop filters SignalDeclStmt out by
    // dynamic_cast branch, so this is normally unreachable. If a
    // future refactor routes signals here, the no-op keeps the
    // existing behavior intact rather than falling through to the
    // "Unsupported statement" assertion. Mirrors the FunctionDeclStmt
    // defensive guard above.
    if (auto* sig = dynamic_cast<const SignalDeclStmt*>(&stmt)) {
        (void)sig;
        return;
    }
    errorAt(Token{}, "Unsupported statement in codegen");
}

void LuaCodegen::emitVarDecl(const VarDeclStmt& var)
{
    // S5 ED-03 (2026-07-15): single writeLine so the anchor is
    // recorded exactly once for this VarDeclStmt's Lua line.
    std::string out;
    out += "local ";
    out += var.name;
    out += " = ";
    if (var.initializer) {
        out += emitExpr(*var.initializer);
    } else {
        out += "nil";
    }
    writeLine(out);
}

void LuaCodegen::emitIfStmt(const IfStmt& stmt)
{
    std::string header;
    header += "if ";
    header += emitExpr(*stmt.condition);
    header += " then";
    writeLine(header);

    ++_indent;
    emitBlock(stmt.thenBranch);
    --_indent;

    if (!stmt.elseBranch.empty()) {
        writeLine("else");
        ++_indent;
        emitBlock(stmt.elseBranch);
        --_indent;
    }

    writeLine("end");
}

// R5.0 (2026-07-13): `while (cond) { body }` → `while <cond> do ... end`.
//
// Mirrors emitIfStmt's shape: keyword on its own line with the
// condition, body block indented one level, `end` de-dented. The
// condition expression is emitted verbatim — emitExpr wraps BinaryExpr
// in parens, so `while (count < 5) do` is the emitted shape (parens
// are optional in Lua's `while cond do` form but always valid).
//
// Lua's `while cond do ... end` re-evaluates `cond` on each iteration;
// no precomputation is done by codegen.
void LuaCodegen::emitWhileStmt(const WhileStmt& stmt)
{
    // R5.2-B (2026-07-14): top-level `LabelDeclStmt`s in the
    // while-body are hoisted to AFTER the `while` block.
    // The `::L::` markers are NOT emitted inside the loop body
    // because Lua 5.2+ forbids re-declaring a label in the same
    // block (a `while` body is one block across all iterations).
    // Hoisting to AFTER the loop makes `break :L` work: the
    // compiled `goto L` jumps to the label at loop end, falling
    // out of the loop. (`continue :L` is not supported in R5.2-B
    // — the parser rejects it. `continue` itself still works as
    // a bare statement.)
    //
    // S5 ED-03 (2026-07-15): header / `end` are writeLine calls
    // anchored to this WhileStmt's sourceLoc. The hoisted labels
    // after `end` are emitted by `hoistLabelsFromBody` which uses
    // writeLine internally and thus picks up the same anchor.
    std::string header;
    header += "while ";
    header += emitExpr(*stmt.condition);
    header += " do";
    writeLine(header);

    ++_indent;
    emitBlockSkipLabels(stmt.body);
    --_indent;

    writeLine("end");
    hoistLabelsFromBody(stmt.body);
}

// R5.0 (2026-07-13): `for (var i : N) { body }` → `for i = 1, N do ... end`.
// R5.0.1 (2026-07-13): range form `for (var i : start, end) { body }` →
//   `for i = start, (end - 1) do` (half-open [start, end)).
//
// Critical emission rules:
//   - The Logia `var` keyword and the colon are deliberately NOT
//     emitted — Lua's `for` doesn't use `var`; the counter is
//     implicitly declared by the `for` keyword itself.
//   - R5.0 short form: counter starts at 1 (hardcoded) and runs to
//     `bound` inclusive. No step argument is emitted.
//   - R5.0.1 range form: counter starts at `start` and runs to
//     `end - 1` inclusive (so the half-open `[start, end)` is
//     represented using Lua's inclusive numeric-for). The `end - 1`
//     is emitted as a parenthesized expression to avoid precedence
//     surprises with arithmetic in the bound (e.g. `end = n*2`
//     emits `for i = 0, (n * 2 - 1) do`).
//   - `bound` / `start` / `end` are emitted via emitExpr, so any
//     Logia expression reducing to a number is accepted (literal,
//     identifier, function call, arithmetic).
//   - Lua's `for i = a, b do ... end` already provides the lexical
//     scope for `i` (loop-local); no codegen-side scope marker is
//     required.
//
// Edge cases:
//   - By R5.2-C (2026-07-14) the analyzer guarantees the bound
//     statically reduces to int, so all numeric-for coercion is
//     now impossible at runtime.
//   - `bound == 0` / `bound < 1` is still legal (Lua skips the body).
//   - `start >= end` (i.e. `start > end - 1`) is still legal (Lua
//     skips the body).
//   - Non-integer bounds are now rejected at compile time by
//     SemanticAnalyzer::validateForBound (ErrorCode::TypeMismatch).
void LuaCodegen::emitForStmt(const ForStmt& stmt)
{
    // R5.2-B (2026-07-14): hoist top-level LabelDeclStmts out of
    // the for-body to AFTER the `for` block. See emitWhileStmt
    // for the rationale.
    //
    // S5 ED-03 (2026-07-15): header / `end` are writeLine calls
    // anchored to this ForStmt's sourceLoc. Hoisted labels pick up
    // the same anchor through `hoistLabelsFromBody`'s writeLine.
    std::string header;
    header += "for ";
    header += stmt.counterName;
    header += " = ";
    if (stmt.start) {
        // R5.0.1 range form: emit `start, (end - 1)`.
        // R5.2-D (2026-07-14): emit `, step` after the half-open
        // bound when step is present. Analyzer guarantees step is
        // a positive int constant by this point (see
        // SemanticAnalyzer.cpp::analyzeForStmt), so Lua never sees
        // a non-positive or non-int step. Static-only — no runtime
        // `if step <= 0` defensive check is injected.
        header += emitExpr(*stmt.start);
        header += ", (";
        header += emitExpr(*stmt.bound);
        header += ") - 1";
        if (stmt.step) {
            header += ", ";
            header += emitExpr(*stmt.step);
        }
    } else {
        // R5.0 short form: emit `1, bound`.
        header += "1, ";
        header += emitExpr(*stmt.bound);
    }
    header += " do";
    writeLine(header);

    ++_indent;
    emitBlockSkipLabels(stmt.body);
    --_indent;

    writeLine("end");
    hoistLabelsFromBody(stmt.body);
}

// R5.1 (2026-07-13): `break;` → Lua `break`.
// R5.2-B (2026-07-14): `break :L` → `goto L`. Lua 5.2+ supports
// `goto` natively; this is the only way to exit an outer loop
// from a nested loop body. The parser's loopDepth gate +
// analyzer's label-visibility check together guarantee the
// label exists at codegen time.
void LuaCodegen::emitBreakStmt(const BreakStmt& stmt)
{
    if (stmt.label.empty()) {
        writeLine("break");
    } else {
        std::string out;
        out += "goto ";
        out += stmt.label;
        writeLine(out);
    }
}

// R5.1 (2026-07-13): `continue;` → Lua `continue`.
// R5.2-B (2026-07-14): same optional `:LABEL` extension as break.
void LuaCodegen::emitContinueStmt(const ContinueStmt& stmt)
{
    if (stmt.label.empty()) {
        writeLine("continue");
    } else {
        std::string out;
        out += "goto ";
        out += stmt.label;
        writeLine(out);
    }
}

// R5.2-A (2026-07-13): explicit `do ... end` shell. The body is
// emitted via the existing emitBlock helper (just iterates the
// StmtPtr vector). Indent is preserved by the surrounding
// LuaCodegen::indent() state — same convention as while/for
// bodies (see emitWhileStmt at L310, emitForStmt at L353).
//
// `do` is a pure block scope keyword in Lua (not a do-while loop);
// the parser already ensures the AST shape is correct.
void LuaCodegen::emitBlockStmt(const BlockStmt& stmt)
{
    writeLine("do");
    ++_indent;
    emitBlock(stmt.body);
    --_indent;
    writeLine("end");
}

// R5.2-B (2026-07-14): `::NAME::` shell. Lua 5.2+ supports label
// declarations natively. Same indent convention as `do/end` (the
// label sits at the same indent as the surrounding statement).
void LuaCodegen::emitLabelDeclStmt(const LabelDeclStmt& stmt)
{
    std::string out;
    out += "::";
    out += stmt.name;
    out += "::";
    writeLine(out);
}

void LuaCodegen::emitReturnStmt(const ReturnStmt& stmt)
{
    if (stmt.value) {
        std::string out;
        out += "return ";
        out += emitExpr(*stmt.value);
        writeLine(out);
    } else {
        writeLine("return");
    }
}

void LuaCodegen::emitExprStmt(const ExprStmt& stmt)
{
    if (!stmt.expr) {
        return;
    }

    if (auto* bin = dynamic_cast<BinaryExpr*>(stmt.expr.get())) {
        TokenType op = bin->op.type;
        if (op == TokenType::Equal ||
            op == TokenType::PlusEqual || op == TokenType::MinusEqual ||
            op == TokenType::StarEqual || op == TokenType::SlashEqual) {

            // LG-05 / S3.3 — AYReflect-backed write for the
            // single-hop `self.<primitiveField>` pattern. Direct
            // assignment / compound assignment both lower to
            // explicit reflect reads + write so the runtime always
            // sees exactly one set call (no temp-around-lightuserdata
            // trap). Chained struct access (self.position.x += ...,
            // etc.) keeps the legacy compound-assign lowering which
            // is a runtime no-op for LG-05 scope.
            //
            // S5 ED-03 (2026-07-15): all paths below emit Lua
            // through `writeLine(...)` so the anchor tracking from
            // emitStmt() records this ExprStmt's sourceLoc for the
            // emitted line(s). Compound assigns emit TWO Lua lines
            // (the `local __tmp = ...` read+op and the
            // `ayt_reflect_set_field(...)` write-back); both anchor
            // to the same ExprStmt.sourceLoc — correct: a runtime
            // panic on either line is the same Logia source line.
            if (op == TokenType::Equal
                && isSingleHopSelfFieldExpr(*bin->left)) {
                std::string rhs = emitExpr(*bin->right);
                std::string out;
                out += "ayt_reflect_set_field(";
                out += selfLua();
                out += ", \"";
                out += _currentHostTypeName;
                out += "\", \"";
                out += singleHopSelfFieldName(*bin->left);
                out += "\", ";
                out += rhs;
                out += ")";
                writeLine(out);
                return;
            }
            if (isSingleHopSelfFieldExpr(*bin->left)
                && (op == TokenType::PlusEqual || op == TokenType::MinusEqual
                    || op == TokenType::StarEqual || op == TokenType::SlashEqual)) {
                // self.field <op>= rhs  →
                //   local __tmp = ayt_reflect_get_field(self, "T", "f") <op> rhs
                //   ayt_reflect_set_field(self, "T", "f", __tmp)
                std::string cur = "ayt_reflect_get_field(";
                cur += selfLua();
                cur += ", \"";
                cur += _currentHostTypeName;
                cur += "\", \"";
                cur += singleHopSelfFieldName(*bin->left);
                cur += "\")";
                std::string opName = tokenOpName(op);
                std::string rhs = emitExpr(*bin->right);
                std::string tmp = freshTmp("compound");
                std::string line1;
                line1 += "local ";
                line1 += tmp;
                line1 += " = ";
                line1 += cur;
                line1 += " ";
                line1 += opName.substr(0, opName.size() - 1);  // strip trailing '='
                line1 += " ";
                line1 += rhs;
                writeLine(line1);
                std::string line2;
                line2 += "ayt_reflect_set_field(";
                line2 += selfLua();
                line2 += ", \"";
                line2 += _currentHostTypeName;
                line2 += "\", \"";
                line2 += singleHopSelfFieldName(*bin->left);
                line2 += "\", ";
                line2 += tmp;
                line2 += ")";
                writeLine(line2);
                return;
            }

            // S3.11: multi-hop `self.<f1>.<f2>...<leaf> = <rhs>` and
            // `self.<...> <op>= <rhs>` lower to the chain reflect
            // helpers, parallel to the S3.10 single-hop blocks
            // above. The RHS itself can contain chain reads
            // (e.g. `self.position.y + self.jump_force * dt`),
            // which `emitExpr` recursively rewrites via Step 3 +
            // the existing single-hop MemberExpr rule.
            std::vector<std::string> chainNames;
            std::size_t hops = 0;
            if (!_currentHostTypeName.empty()
                && isSelfFieldChainExpr(*bin->left, chainNames, hops)) {
                if (op == TokenType::Equal) {
                    std::string rhs = emitExpr(*bin->right);
                    std::string out;
                    out += "ayt_reflect_set_field_chain(";
                    out += selfLua();
                    out += ", \"";
                    out += _currentHostTypeName;
                    out += "\"";
                    for (const auto& n : chainNames) {
                        out += ", \"";
                        out += n;
                        out += "\"";
                    }
                    out += ", ";
                    out += rhs;
                    out += ")";
                    writeLine(out);
                } else {
                    // Compound assign on chain: get → op → set, all
                    // via the chain helpers.
                    std::string rhs = emitExpr(*bin->right);
                    std::string tmp = freshTmp("chain_compound");
                    std::string opName = tokenOpName(op);
                    // local __tmp = get_chain(self, "...", "f1", ..., "leaf") <op> rhs
                    std::string line1;
                    line1 += "local ";
                    line1 += tmp;
                    line1 += " = ayt_reflect_get_field_chain(";
                    line1 += selfLua();
                    line1 += ", \"";
                    line1 += _currentHostTypeName;
                    line1 += "\"";
                    for (const auto& n : chainNames) {
                        line1 += ", \"";
                        line1 += n;
                        line1 += "\"";
                    }
                    line1 += ") ";
                    // strip trailing '=' from opName (e.g. "+=" -> "+")
                    line1 += opName.substr(0, opName.size() - 1);
                    line1 += " ";
                    line1 += rhs;
                    writeLine(line1);
                    // ayt_reflect_set_field_chain(self, "...", "f1", ..., "leaf", __tmp)
                    std::string line2;
                    line2 += "ayt_reflect_set_field_chain(";
                    line2 += selfLua();
                    line2 += ", \"";
                    line2 += _currentHostTypeName;
                    line2 += "\"";
                    for (const auto& n : chainNames) {
                        line2 += ", \"";
                        line2 += n;
                        line2 += "\"";
                    }
                    line2 += ", ";
                    line2 += tmp;
                    line2 += ")";
                    writeLine(line2);
                }
                return;
            }

            std::string rhs;
            if (op == TokenType::Equal) {
                rhs = emitExpr(*bin->right);
            } else {
                rhs = emitCompoundRhs(*bin->left, tokenOpName(op), *bin->right);
            }
            std::string target = emitAssignmentTarget(*bin->left);
            std::string out;
            out += target;
            out += " = ";
            out += rhs;
            writeLine(out);
            return;
        }
    }

    // S5 ED-03 (2026-07-15): fall-through case — bare expression
    // statement (e.g. `self.method(args)`) emits one Lua line.
    std::string out;
    out += emitExpr(*stmt.expr);
    writeLine(out);
}

// ============================================================
// Expressions
// ============================================================

std::string LuaCodegen::emitExpr(const Expr& expr)
{
    if (auto* b = dynamic_cast<const BinaryExpr*>(&expr)) {
        std::string l = emitExpr(*b->left);
        std::string r = emitExpr(*b->right);
        std::string out;
        out.reserve(l.size() + r.size() + 4);
        out += "(";
        out += l;
        out += " ";
        out += tokenOpName(b->op.type);
        out += " ";
        out += r;
        out += ")";
        return out;
    }
    if (auto* u = dynamic_cast<const UnaryExpr*>(&expr)) {
        std::string inner = emitExpr(*u->operand);
        std::string out;
        if (u->op.type == TokenType::Minus) {
            out += "(-";
            out += inner;
            out += ")";
        } else if (u->op.type == TokenType::Bang) {
            out += "(not ";
            out += inner;
            out += ")";
        } else {
            errorAt(u->op, "Unsupported unary operator");
            return "nil";
        }
        return out;
    }
    if (auto* c = dynamic_cast<const CallExpr*>(&expr)) {
        // S4.1 (2026-07-15): ambient free-function calls `emit(...)`
        // and `connect(...)` rewrite to `__ay_emit(self, ...)` /
        // `__ay_connect(self, ..., handler)` — codegen inserts `self`
        // as the receiver arg because Logia grammar has no colon-call
        // (Q-1 forced this; see plan §14.5). D-2 handler self-bind is
        // realized by `__ay_emit` stamping `__ay_bound_self` and
        // helper-body codegen rewriting bare `self` to that slot
        // (connect wrap alone cannot inject into a top-level helper).
        // The analyzer has already validated signal-existence, arity,
        // and arg-type compat by this point, so we don't re-check here.
        if (c->ambientCall == CallExpr::AmbientCallKind::Emit) {
            std::string out = "__ay_emit(self";
            for (const auto& a : c->args) {
                out += ", ";
                out += emitExpr(*a);
            }
            out += ")";
            return out;
        }
        if (c->ambientCall == CallExpr::AmbientCallKind::Connect) {
            // emit("__ay_connect(self, \"<name>\", function(...) "
            //      "return <handler>(...) end)")
            // The wrapper is created inside the lifecycle body. D-2
            // self-bind for the *handler body* is NOT done by
            // capturing an upvalue here — a top-level `function
            // on_tap()` cannot see that upvalue. Instead `__ay_emit`
            // sets `__ay_bound_self` and helper codegen rewrites
            // bare `self` to that slot. The wrap still exists so
            // signal args forward via `...` unchanged.
            if (c->args.size() != 2) {
                // Defensive — analyzer should have caught this; if it
                // didn't, fall through to bare Lua dispatch rather
                // than segfault on bad indexing.
                std::string out = emitExpr(*c->callee);
                out += "(";
                bool first = true;
                for (const auto& a : c->args) {
                    if (!first) out += ", ";
                    out += emitExpr(*a);
                    first = false;
                }
                out += ")";
                return out;
            }
            std::string out = "__ay_connect(self, ";
            out += emitExpr(*c->args[0]);
            out += ", function(...) return ";
            out += emitExpr(*c->args[1]);
            out += "(...) end)";
            return out;
        }
        // S4.1b (2026-07-18): disconnect lowering. The id arg is
        // emitted verbatim (typically `h` from `var h: int = connect(...)`);
        // the runtime helper does an O(1) tombstone scan across all
        // signal-name lists on this instance. We don't validate the
        // arg's Lua type here — analyzer already enforced `int` at
        // the var-decl site, and the helper is a safe no-op on
        // mismatched ids (it's just a linear search that finds
        // nothing).
        if (c->ambientCall == CallExpr::AmbientCallKind::Disconnect) {
            if (c->args.size() != 1) {
                // Defensive — analyzer should have caught this; fall
                // back to bare Lua dispatch rather than mis-emitting.
                std::string out = emitExpr(*c->callee);
                out += "(";
                bool first = true;
                for (const auto& a : c->args) {
                    if (!first) out += ", ";
                    out += emitExpr(*a);
                    first = false;
                }
                out += ")";
                return out;
            }
            std::string out = "__ay_disconnect(self, ";
            out += emitExpr(*c->args[0]);
            out += ")";
            return out;
        }
        // S3.12 (track R2 §5.7.4): `self.method(args)` rewrites to
        // `ayt_reflect_call_method(self, "<Type>", "<method>", args...)`.
        // The analyzer stamps CallExpr::resolvedMethod only when the
        // callee is a MemberExpr on self AND the method exists on the
        // host type's reflect registry; otherwise the analyzer leaves
        // resolvedMethod=null and codegen falls back to bare Lua
        // dispatch (which still works for non-reflected method names
        // — they just won't actually invoke the C++ method).
        if (c->resolvedMethod != nullptr
            && c->resolvedMethodOwnerName != nullptr) {
            std::string out = "ayt_reflect_call_method(";
            out += selfLua();
            out += ", \"";
            out += c->resolvedMethodOwnerName;
            out += "\", \"";
            out += c->resolvedMethod->getName();
            out += "\"";
            for (const auto& a : c->args) {
                out += ", ";
                out += emitExpr(*a);
            }
            out += ")";
            return out;
        }
        std::string callee = emitExpr(*c->callee);
        std::string out;
        out += callee;
        out += "(";
        bool first = true;
        for (const auto& a : c->args) {
            if (!first) out += ", ";
            out += emitExpr(*a);
            first = false;
        }
        out += ")";
        return out;
    }
    if (auto* m = dynamic_cast<const MemberExpr*>(&expr)) {
        // S3.11 (LG-05 extended): multi-hop `self.<f1>.<f2>...<leaf>`
        // rewrites to `ayt_reflect_get_field_chain(self, "<Host>",
        // "<f1>", ..., "<leaf>")`. Probe before the single-hop gate
        // because the chain probe is more restrictive (>=2 hops,
        // every node resolvedField-stamped, leaf primitive) — single-
        // hop stays on the S3.10 path below.
        std::vector<std::string> chainNames;
        std::size_t hops = 0;
        if (!_currentHostTypeName.empty()
            && isSelfFieldChainExpr(*m, chainNames, hops)) {
            std::string out;
            out += "ayt_reflect_get_field_chain(";
            out += selfLua();
            out += ", \"";
            out += _currentHostTypeName;
            out += "\"";
            for (const auto& n : chainNames) {
                out += ", \"";
                out += n;
                out += "\"";
            }
            out += ")";
            return out;
        }
        // LG-05 / S3.3 — AYReflect-backed read: single-hop
        // `self.<primitiveField>` rewrites to the bridge's
        // reflect call. The `resolvedField` stamp comes from
        // SemanticAnalyzer; we additionally require the leaf type
        // to have no fields of its own (primitives like int/float/
        // bool). Struct members are out of S3.3 scope — kept as
        // bare Lua member access which becomes a runtime no-op
        // on the lightuserdata (matches S2.5 behavior).
        if (auto* objId = dynamic_cast<const IdentifierExpr*>(m->object.get())) {
            if (objId->name == "self"
                && !_currentHostTypeName.empty()
                && m->resolvedField != nullptr
                && m->resolvedType != nullptr
                && m->resolvedType->getFieldCount() == 0) {
                std::string out;
                out += "ayt_reflect_get_field(";
                out += selfLua();
                out += ", \"";
                out += _currentHostTypeName;
                out += "\", \"";
                out += m->member;
                out += "\")";
                return out;
            }
        }
        std::string obj = emitExpr(*m->object);
        std::string out;
        out += obj;
        out += ".";
        out += m->member;
        return out;
    }
    if (auto* i = dynamic_cast<const IndexExpr*>(&expr)) {
        std::string obj = emitExpr(*i->object);
        std::string idx = emitExpr(*i->index);
        std::string out;
        out += obj;
        out += "[";
        out += idx;
        out += "]";
        return out;
    }
    if (auto* id = dynamic_cast<const IdentifierExpr*>(&expr)) {
        if (id->name == "self") return selfLua();
        return id->name;
    }
    if (auto* lit = dynamic_cast<const LiteralExpr*>(&expr)) {
        if (std::holds_alternative<bool>(lit->value)) {
            return std::get<bool>(lit->value) ? "true" : "false";
        }
        if (std::holds_alternative<int>(lit->value)) {
            return std::to_string(std::get<int>(lit->value));
        }
        if (std::holds_alternative<float>(lit->value)) {
            std::ostringstream oss;
            oss << std::get<float>(lit->value);
            return oss.str();
        }
        if (std::holds_alternative<std::string>(lit->value)) {
            return escapeString(std::get<std::string>(lit->value));
        }
        return "nil";
    }
    if (auto* t = dynamic_cast<const TableExpr*>(&expr)) {
        // S3.12+R3: emit `{k1=v1, k2=v2, ...}` where each `ki`
        // is a bareword identifier. Lua's table-constructor record
        // syntax `name=value` requires the key to be an identifier
        // (no quotes). The bridge reads each key with lua_getfield
        // after the table is on the stack; lua_getfield works on
        // both quoted-string and bareword table keys.
        std::string out = "{";
        for (size_t i = 0; i < t->entries.size(); ++i) {
            if (i > 0) out += ", ";
            const auto& e = t->entries[i];
            if (e.key) {
                // Identifier key — emit as bareword (no quotes).
                std::string keyName;
                if (auto* id = dynamic_cast<const IdentifierExpr*>(e.key.get())) {
                    keyName = id->name;
                } else {
                    // R3.0 only supports identifier keys; otherwise
                    // emit as `[expr] = value` syntax (Lua generic
                    // table constructor).
                    out += "[";
                    out += emitExpr(*e.key);
                    out += "] = ";
                    out += emitExpr(*e.value);
                    continue;
                }
                out += keyName;
                out += " = ";
            }
            out += emitExpr(*e.value);
        }
        out += "}";
        return out;
    }
    errorAt(Token{}, "Unsupported expression in codegen");
    return "nil";
}

// ============================================================
// Compound assignment lowering
//
// `transform.position.y += jump_force * dt` lowers to:
//   local __tmp_0 = transform.position
//   __tmp_0.y = __tmp_0.y + (jump_force * dt)
//
// emitAssignmentTarget() emits the prefix-statement fragment that creates
// the temporary and returns the Lua expression to use as the LHS.
// ============================================================

namespace {

bool collectMemberChain(const Expr& e, std::vector<std::string>& members)
{
    if (auto* m = dynamic_cast<const MemberExpr*>(&e)) {
        members.push_back(m->member);
        return collectMemberChain(*m->object, members);
    }
    return !members.empty();
}

} // namespace

std::string LuaCodegen::emitAssignmentTarget(const Expr& target)
{
    std::vector<std::string> members;
    if (!collectMemberChain(target, members)) {
        return emitExpr(target);
    }
    std::vector<std::string> rev(members.rbegin(), members.rend());
    std::string tmpName = freshTmp("lhs");
    // S5 ED-03 (2026-07-15): emit the temp declaration as a
    // proper Lua line through writeLine so the anchor tracking
    // picks it up. The caller (emitExprStmt's compound-assign
    // branch) wraps this helper in an ExprStmt whose sourceLoc
    // is set by emitStmt(); the temp line anchors to that same
    // Logia source line, which is correct — the `local __tmp =
    // ...` line is part of the same compound-assign statement.
    std::string decl;
    decl += "local ";
    decl += tmpName;
    decl += " = ";
    if (auto* m = dynamic_cast<const MemberExpr*>(&target)) {
        decl += emitExpr(*m->object);
        for (size_t i = 1; i + 1 < rev.size(); ++i) {
            decl += ".";
            decl += rev[i];
        }
    } else {
        decl += "nil";
    }
    writeLine(decl);

    std::string out;
    out += tmpName;
    out += ".";
    out += rev.back();
    return out;
}

// ============================================================
// LG-05 / S3.3 helpers
// ------------------------------------------------------------
// isSingleHopSelfFieldExpr / singleHopSelfFieldName probe the AST
// shape directly and never touch `_currentHostTypeName`, so they
// behave identically whether or not the script name resolved in
// AYReflect. The reflect-call rewrite in emitMemberExpr /
// emitExprStmt gates on `_currentHostTypeName` non-empty — here we
// just ask "is this a one-hop self.<primitiveField>?" and let the
// callers decide.
// ============================================================

bool LuaCodegen::isSingleHopSelfFieldExpr(const Expr& e)
{
    auto* m = dynamic_cast<const MemberExpr*>(&e);
    if (!m) return false;
    auto* objId = dynamic_cast<const IdentifierExpr*>(m->object.get());
    if (!objId || objId->name != "self") return false;
    if (m->resolvedField == nullptr) return false;
    if (m->resolvedType == nullptr) return false;
    // Primitive leaf only (int/float/bool/etc.). Chained struct
    // subfield access keeps the legacy compound-assign lowering,
    // which is a runtime no-op for S3.3 (out of scope).
    return m->resolvedType->getFieldCount() == 0;
}

std::string LuaCodegen::singleHopSelfFieldName(const Expr& e)
{
    auto* m = dynamic_cast<const MemberExpr*>(&e);
    return m ? m->member : std::string();
}

// S3.11: probe a multi-hop `self.<f1>.<f2>...<leaf>` chain. Returns
// true and fills `fieldNames` (root→leaf order) when every MemberExpr
// in the chain has `resolvedField != nullptr` (analyzer stamped the
// AYReflect IFieldInfo for each hop) and the leaf's resolvedType is
// a primitive (getFieldCount() == 0). `hopCount >= 2` gate keeps
// `self.field` (single hop) on the existing S3.10 path; otherwise
// every chain would be re-routed to the new helpers and S3.10 tests
// would see different codegen output.
bool LuaCodegen::isSelfFieldChainExpr(const Expr& e,
                                     std::vector<std::string>& fieldNames,
                                     std::size_t& hopCount)
{
    fieldNames.clear();
    hopCount = 0;

    // Walk the chain from the leaf inward; collect names in reverse.
    std::vector<std::string> reversed;
    const Expr* cur = &e;
    while (auto* m = dynamic_cast<const MemberExpr*>(cur)) {
        if (m->resolvedField == nullptr) {
            return false;  // analyzer couldn't resolve this hop
        }
        reversed.push_back(m->member);
        ++hopCount;
        cur = m->object.get();
    }

    // The root must be the `self` identifier (NOT another member expr,
    // NOT an arbitrary expression — chain must be `self.*`).
    auto* rootId = dynamic_cast<const IdentifierExpr*>(cur);
    if (!rootId || rootId->name != "self") {
        return false;
    }

    // Require primitive leaf so the runtime helper can call
    // pushFieldPrimitive on the final hop.
    auto* leafM = dynamic_cast<const MemberExpr*>(&e);
    if (!leafM || leafM->resolvedType == nullptr
        || leafM->resolvedType->getFieldCount() != 0) {
        return false;
    }

    if (hopCount < 2) {
        return false;  // single-hop stays on the S3.10 path
    }

    // Reverse to root→leaf order.
    fieldNames.assign(reversed.rbegin(), reversed.rend());
    return true;
}

std::string LuaCodegen::emitCompoundRhs(const Expr& target,
                                       const std::string& op,
                                       const Expr& rhs)
{
    std::vector<std::string> members;
    std::string lhsStr;
    if (collectMemberChain(target, members)) {
        std::vector<std::string> rev(members.rbegin(), members.rend());
        if (auto* m = dynamic_cast<const MemberExpr*>(&target)) {
            lhsStr = emitExpr(*m->object);
            for (size_t i = 1; i < rev.size(); ++i) {
                lhsStr += ".";
                lhsStr += rev[i];
            }
        }
    } else {
        lhsStr = emitExpr(target);
    }
    std::string rhsStr = emitExpr(rhs);
    std::string out;
    out += lhsStr;
    out += " ";
    out += op;
    out += " ";
    out += rhsStr;
    return out;
}

std::string LuaCodegen::freshTmp(const std::string& hint)
{
    ++_tmpCounter;
    std::string name = "__tmp_";
    if (!hint.empty()) {
        name += hint;
        name += "_";
    }
    name += std::to_string(_tmpCounter);
    return name;
}

const char* LuaCodegen::selfLua() const
{
    return _emittingScriptHelper ? "__ay_bound_self" : "self";
}

// ============================================================
// Helpers
// ============================================================

void LuaCodegen::line(const std::string& s)
{
    indent();
    _out += s;
    _out += "\n";
}

// S5 ED-03 (2026-07-15): anchor-tracking single-line writer. Replaces
// the previously-unused `line()` helper for all post-ED-03 emit paths.
// Performs indent + write + newline + bumps `_luaLineCount` + records
// `_currentAnchor` at the new index in `_sourceMap`. The 1-based
// vector indexing matches Lua's line numbering directly — callers
// looking up `sourceMap.lookup(luaLine)` for Lua line `N` get the
// Logia anchor without an off-by-one.
//
// Used as the only "emit one Lua line" entry point after S5 ED-03;
// the multi-write patterns (e.g. emitVarDecl writing "local " + name
// + " = " + expr + "\n" in five separate `_out +=` calls) collapse
// into a single `writeLine("local NAME = EXPR")` call. Where a
// single statement emits multiple lines (e.g. compound assignment
// with a `local __tmp = ...` then `ayt_reflect_set_field(...)`),
// each line is its own `writeLine` call — both anchor to the same
// `_currentAnchor` set by `emitStmt()` for that statement.
void LuaCodegen::writeLine(const std::string& content)
{
    indent();
    _out += content;
    _out += "\n";
    ++_luaLineCount;
    // Grow on demand; index N stored at _sourceMap[N] for Lua line N
    // (1-based). Index 0 is reserved (left default-constructed as
    // the empty SourceLocation sentinel).
    if (static_cast<int>(_sourceMap.luaLineToSource.size()) <= _luaLineCount) {
        _sourceMap.luaLineToSource.resize(_luaLineCount + 1);
    }
    _sourceMap.luaLineToSource[_luaLineCount] = _currentAnchor;
}

SourceLocation LogiaSourceMap::lookup(int luaLine) const
{
    if (luaLine <= 0 || luaLine >= static_cast<int>(luaLineToSource.size())) {
        return {};
    }
    return luaLineToSource[luaLine];
}

// S5 ED-03 (2026-07-15): blank-line emitter used between top-level
// lifecycle functions / helpers for generated-Lua readability. A
// blank Lua line has no Logia source location (it's codegen
// formatting, not user-authored content), so we record an empty
// anchor rather than inheriting the previous Stmt's anchor. This
// matches the codegen preamble / epilogue convention (also anchored
// to `{}`) — a runtime panic on a blank Lua line is structurally
// impossible because blank lines never execute.
void LuaCodegen::writeBlankLine()
{
    _out += "\n";
    ++_luaLineCount;
    if (static_cast<int>(_sourceMap.luaLineToSource.size()) <= _luaLineCount) {
        _sourceMap.luaLineToSource.resize(_luaLineCount + 1);
    }
    // index [_luaLineCount] already left default-constructed (the
    // vector::resize above leaves new slots as SourceLocation{}).
}

// S5 ED-03 (2026-07-15): codegen preamble / epilogue writer. The
// generated-Lua preamble (`-- Auto-generated ...`, `local M = {}`)
// and epilogue (`return M`) are codegen-internal — they have no
// Logia source location. Anchor them to {} so the bridge's
// translation correctly reports "untranslatable" for any panic
// on those lines (which would be a codegen bug, not a
// user-source bug).
void LuaCodegen::writeNoAnchor(const std::string& content)
{
    _out += content;
    _out += "\n";
    ++_luaLineCount;
    if (static_cast<int>(_sourceMap.luaLineToSource.size()) <= _luaLineCount) {
        _sourceMap.luaLineToSource.resize(_luaLineCount + 1);
    }
    // index [_luaLineCount] left default-constructed.
}

void LuaCodegen::indent()
{
    for (int i = 0; i < _indent; ++i) _out += "    ";
}

void LuaCodegen::dedent()
{
    if (_indent > 0) --_indent;
}

std::string LuaCodegen::escapeString(const std::string& s) const
{
    std::string out;
    out.reserve(s.size() + 2);
    out += '"';
    for (char c : s) {
        switch (c) {
        case '"':  out += "\\\""; break;
        case '\\': out += "\\\\"; break;
        case '\n': out += "\\n";  break;
        case '\r': out += "\\r";  break;
        case '\t': out += "\\t";  break;
        default:
            if (static_cast<unsigned char>(c) < 0x20) {
                char buf[8];
                std::snprintf(buf, sizeof(buf), "\\x%02X", static_cast<unsigned char>(c));
                out += buf;
            } else {
                out += c;
            }
        }
    }
    out += '"';
    return out;
}

void LuaCodegen::errorAt(const Token& tok, const std::string& message)
{
    CompilerError err;
    err.code = ErrorCode::InvalidStatement;
    err.message = message;
    err.line = tok.line;
    err.column = tok.column;
    _errors.push_back(err);
}

} // namespace ayt::script::logia