// AYLuaCodegen.cpp - AST → Lua source generator (S2.5)
//
// S2.5 redesign: `component` → `script`, `export var` removed. All `var`
// declarations become `local` Lua variables. `self` is the canonical way
// to access the bound ScriptComponent; field access is left as bare Lua
// member syntax (`self.field`) for now — S3 will route it through
// AYReflect-backed accessors.

#include "logia/AYLuaCodegen.h"

// LG-05 / S3.3: full ITypeInfo definition so we can call
// getFieldCount() on the resolved leaf type of `self.<field>`
// and decide between the reflect-call rewrite and the legacy
// bare-member codegen.
#include "ayreflect/IReflect.h"

#include <cstdio>
#include <sstream>
#include <utility>

namespace ayt::script::logia
{

namespace {

const char* tokenOpName(TokenType t)
{
    switch (t) {
    case TokenType::Plus:       return "+";
    case TokenType::Minus:      return "-";
    case TokenType::Star:       return "*";
    case TokenType::Slash:      return "/";
    case TokenType::Percent:    return "%";
    case TokenType::Equal:      return "=";
    case TokenType::PlusEqual:  return "+=";
    case TokenType::MinusEqual: return "-=";
    case TokenType::StarEqual:  return "*=";
    case TokenType::SlashEqual: return "/=";
    case TokenType::EqualEqual: return "==";
    case TokenType::BangEqual:  return "~=";
    case TokenType::Less:       return "<";
    case TokenType::LessEqual:  return "<=";
    case TokenType::Greater:    return ">";
    case TokenType::GreaterEqual: return ">=";
    case TokenType::And:        return "and";
    case TokenType::Or:         return "or";
    default: return "?";
    }
}

} // namespace

// R5.2-B (2026-07-14): emit `::L::` markers for each top-level
// LabelDeclStmt in `body`, at the current indent. The caller
// (emitWhileStmt / emitForStmt) invokes this AFTER writing the
// loop's `end` keyword, so the label lands at the same indent
// as the loop header — i.e. immediately AFTER the loop. This
// is what makes `break :L` work: the compiled `goto L` jumps to
// the label at loop end, falling out of the loop.
//
// We do NOT emit the label inside the loop body because Lua
// 5.2+ forbids re-declaring a label in the same block (a
// loop's body is one block across all iterations).
//
// Implementation note: the body comes in as `const
// std::vector<StmtPtr>&` (the loop's body field is read-only).
// Copying `unique_ptr` is forbidden, so we cannot build a
// "stripped body" vector — the caller walks the body twice
// (emitBlockSkipLabels iterates the body and skips labels;
// this helper iterates the body and emits only labels).
void LuaCodegen::hoistLabelsFromBody(const std::vector<StmtPtr>& body)
{
    for (const auto& s : body) {
        if (auto* ld = dynamic_cast<const LabelDeclStmt*>(s.get())) {
            indent();
            _out += "::";
            _out += ld->name;
            _out += "::\n";
        }
    }
}

LuaCodegen::LuaCodegen(LuaCodegenOptions options)
    : _options(std::move(options)) {}

LuaCodegenResult LuaCodegen::generate(const Program& program)
{
    LuaCodegenResult result;
    _errors.clear();
    _out.clear();
    _indent = 0;
    _tmpCounter = 0;

    _out += "-- Auto-generated by AYLuaCodegen from ";
    _out += _options.scriptName.empty() ? std::string("Logia source") : _options.scriptName;
    _out += "\n";
    _out += "local M = {}\n\n";

    // S2.5: a `.logia` file produces exactly one module (one `script`
    // block). Multiple scripts in one file generate multiple modules —
    // call once per script from the loader. For now, generate only the
    // first script (the parser produces a single `ScriptDecl` per file
    // in practice; the loader can re-enter `generate` with another
    // Program if needed).
    if (program.scripts.empty()) {
        CompilerError err;
        err.code = ErrorCode::InvalidStatement;
        err.message = "Logia file contains no script declaration";
        err.line = 0;
        err.column = 0;
        _errors.push_back(err);
    } else {
        emitScript(*program.scripts[0]);
    }

    _out += "\nreturn M\n";

    result.errors = _errors;
    result.source = _out;
    result.success = _errors.empty();
    return result;
}

// ============================================================
// Scripts
// ============================================================

void LuaCodegen::emitScript(const ScriptDecl& script)
{
    // LG-05 / S3.3: record the host type name for `self.<field>`
    // reflect-call rewrites. Scope is per-script — reset on exit.
    _currentHostTypeName = script.hostTypeName;

    // Var declarations first (locals). Lifecycle functions come next.
    for (const auto& member : script.members) {
        if (auto* var = dynamic_cast<VarDeclStmt*>(member.get())) {
            emitLocalVar(*var);
        }
    }

    for (const auto& member : script.members) {
        if (auto* fn = dynamic_cast<LifecycleFuncDecl*>(member.get())) {
            emitLifecycleFunc(*fn);
            _out += "\n";
        }
    }

    // 2026-07-11 audit fix: user-defined script-block-scope helpers.
    // Emitted after lifecycles so they're hoisted before the first
    // `M.on_start(...)` reference (Lua hoists top-level function
    // statements anyway, but ordering improves readability). Lifecycle
    // bodies call them via bare name (`doubleIt(21)`), and the bare
    // name resolves to the top-level `function doubleIt(...) ... end`
    // we emit here.
    for (const auto& member : script.members) {
        if (auto* fn = dynamic_cast<const FunctionDeclStmt*>(member.get())) {
            emitFunctionDecl(*fn);
            _out += "\n";
        }
    }
}

void LuaCodegen::emitLocalVar(const VarDeclStmt& var)
{
    indent();
    _out += "local ";
    _out += var.name;
    _out += " = ";
    if (var.initializer) {
        _out += emitExpr(*var.initializer);
    } else {
        _out += "nil";
    }
    _out += "\n";
}

void LuaCodegen::emitLifecycleFunc(const LifecycleFuncDecl& func)
{
    indent();
    _out += "function M.";
    _out += lifecycleKindName(func.kind);
    // S3.8b: when the host context's `expectSelf` is false (Tool
    // host), emit a parameter list with NO `self`. The ToolRunner
    // passes `receiver = nullptr` at call time — emitting `self`
    // here would mismatch Lua's call arity (`function M.run(self)`
    // expects one arg, the bridge calls with zero).
    //
    // Component / System / EventHandler hosts keep the S2.5 shape
    // `function M.on_*(self[, ...legacyParams])`. Legacy params from
    // the parser are still forwarded for forward-compat with future
    // event-handler signatures (e.g. `on_damage(amount: float)`).
    const bool emitSelf = _options.hostContext.expectSelf;
    if (emitSelf) {
        _out += "(self";
        for (const auto& p : func.params) {
            _out += ", ";
            _out += p.name;
        }
        _out += ")\n";
    } else {
        // No self. Legacy params still go through (the parser only
        // emits them as a documentation affordance, but codegen is
        // the single source of truth — forwarding them keeps the
        // signature shape stable if a future event handler is bound
        // through the same plumbing with expectSelf re-enabled).
        if (func.params.empty()) {
            _out += "()\n";
        } else {
            _out += "(";
            bool first = true;
            for (const auto& p : func.params) {
                if (!first) _out += ", ";
                _out += p.name;
                first = false;
            }
            _out += ")\n";
        }
    }

    ++_indent;
    emitBlock(func.body);
    --_indent;

    indent();
    _out += "end\n";
}

// ============================================================
// Statements
// ============================================================

void LuaCodegen::emitBlock(const std::vector<StmtPtr>& body)
{
    for (const auto& stmt : body) {
        emitStmt(*stmt);
    }
}

// R5.2-B (2026-07-14): like emitBlock, but skips top-level
// LabelDeclStmt nodes. Used by emitWhileStmt / emitForStmt to
// avoid re-emitting labels that have already been hoisted to
// immediately before the loop's `for` / `while` header (Lua
// 5.2+ forbids re-declaring a label in the same block, and a
// loop body is one block across all iterations).
//
// Nested labels (LabelDeclStmt inside an `if` / `do` / nested
// loop) are NOT skipped here — they reach emitStmt via
// emitBlock and are emitted verbatim. Hoisting applies only
// to direct-child labels of the immediate loop body.
void LuaCodegen::emitBlockSkipLabels(const std::vector<StmtPtr>& body)
{
    for (const auto& stmt : body) {
        if (dynamic_cast<const LabelDeclStmt*>(stmt.get())) continue;
        emitStmt(*stmt);
    }
}

// 2026-07-11 audit fix: emit a top-level Lua function for a
// script-block-scope helper. Mirrors `emitLifecycleFunc`'s shape but
// without the `M.` prefix — the function is reachable from every
// lifecycle body in the same module via its bare name.
void LuaCodegen::emitFunctionDecl(const FunctionDeclStmt& fn)
{
    indent();
    _out += "function ";
    _out += fn.name;
    _out += "(";
    for (size_t i = 0; i < fn.params.size(); ++i) {
        if (i > 0) _out += ", ";
        _out += fn.params[i].name;
    }
    _out += ")\n";
    ++_indent;
    for (const auto& s : fn.body) {
        emitStmt(*s);
    }
    --_indent;
    indent();
    _out += "end\n";
}

void LuaCodegen::emitStmt(const Stmt& stmt)
{
    if (auto* v = dynamic_cast<const VarDeclStmt*>(&stmt)) { emitVarDecl(*v); return; }
    if (auto* i = dynamic_cast<const IfStmt*>(&stmt))      { emitIfStmt(*i);   return; }
    // R5.0 (2026-07-13): loop statements. WhileStmt and ForStmt
    // dispatch BEFORE ReturnStmt so a `return` inside a loop body
    // (R5.0.1) would be parsed/handled by parseWhileStmt / parseForStmt
    // itself — no interference here.
    if (auto* w = dynamic_cast<const WhileStmt*>(&stmt))   { emitWhileStmt(*w); return; }
    if (auto* f = dynamic_cast<const ForStmt*>(&stmt))     { emitForStmt(*f);   return; }
    // R5.1 (2026-07-13): break / continue. Lua 5.5 supports both
    // natively (Lua 5.2+ added `continue`). Codegen emits them
    // verbatim — the parser's loopDepth gate has already verified
    // these appear inside a loop body, so the emitted Lua is also
    // guaranteed to be in a valid context.
    if (auto* b = dynamic_cast<const BreakStmt*>(&stmt))    { emitBreakStmt(*b); return; }
    if (auto* c = dynamic_cast<const ContinueStmt*>(&stmt)) { emitContinueStmt(*c); return; }
    // R5.2-A (2026-07-13): block-scope statement. Lowered to Lua
    // 5.2+ native `do ... end`. The Logia-side `do` / `end` /
    // braces in source are consumed by the parser; this emit
    // produces the shell only.
    if (auto* blk = dynamic_cast<const BlockStmt*>(&stmt))   { emitBlockStmt(*blk); return; }
    // R5.2-B (2026-07-14): label declaration. Lowered to Lua
    // 5.2+ `::NAME::` natively. Codegen only writes the marker.
    if (auto* lbl = dynamic_cast<const LabelDeclStmt*>(&stmt)) { emitLabelDeclStmt(*lbl); return; }
    if (auto* r = dynamic_cast<const ReturnStmt*>(&stmt))  { emitReturnStmt(*r); return; }
    if (auto* e = dynamic_cast<const ExprStmt*>(&stmt))    { emitExprStmt(*e); return; }
    // 2026-07-11 audit fix: defensive — parser rejects `function`
    // inside lifecycle bodies, but if codegen ever sees one here
    // (e.g. via a malformed AST forged by a hostile serializer)
    // we still emit clean Lua rather than corrupting the chunk.
    if (auto* fn = dynamic_cast<const FunctionDeclStmt*>(&stmt)) {
        emitFunctionDecl(*fn);
        return;
    }
    errorAt(Token{}, "Unsupported statement in codegen");
}

void LuaCodegen::emitVarDecl(const VarDeclStmt& var)
{
    indent();
    _out += "local ";
    _out += var.name;
    _out += " = ";
    if (var.initializer) {
        _out += emitExpr(*var.initializer);
    } else {
        _out += "nil";
    }
    _out += "\n";
}

void LuaCodegen::emitIfStmt(const IfStmt& stmt)
{
    indent();
    _out += "if ";
    _out += emitExpr(*stmt.condition);
    _out += " then\n";

    ++_indent;
    emitBlock(stmt.thenBranch);
    --_indent;

    if (!stmt.elseBranch.empty()) {
        indent();
        _out += "else\n";
        ++_indent;
        emitBlock(stmt.elseBranch);
        --_indent;
    }

    indent();
    _out += "end\n";
}

// R5.0 (2026-07-13): `while (cond) { body }` → `while <cond> do ... end`.
//
// Mirrors emitIfStmt's shape: keyword on its own line with the
// condition, body block indented one level, `end` de-dented. The
// condition expression is emitted verbatim — emitExpr wraps BinaryExpr
// in parens, so `while (count < 5) do` is the emitted shape (parens
// are optional in Lua's `while cond do` form but always valid).
//
// Lua's `while cond do ... end` re-evaluates `cond` on each iteration;
// no precomputation is done by codegen.
void LuaCodegen::emitWhileStmt(const WhileStmt& stmt)
{
    // R5.2-B (2026-07-14): top-level `LabelDeclStmt`s in the
    // while-body are hoisted to AFTER the `while` block.
    // The `::L::` markers are NOT emitted inside the loop body
    // because Lua 5.2+ forbids re-declaring a label in the same
    // block (a `while` body is one block across all iterations).
    // Hoisting to AFTER the loop makes `break :L` work: the
    // compiled `goto L` jumps to the label at loop end, falling
    // out of the loop. (`continue :L` is not supported in R5.2-B
    // — the parser rejects it. `continue` itself still works as
    // a bare statement.)
    indent();
    _out += "while ";
    _out += emitExpr(*stmt.condition);
    _out += " do\n";

    ++_indent;
    emitBlockSkipLabels(stmt.body);
    --_indent;

    indent();
    _out += "end\n";
    hoistLabelsFromBody(stmt.body);
}

// R5.0 (2026-07-13): `for (var i : N) { body }` → `for i = 1, N do ... end`.
// R5.0.1 (2026-07-13): range form `for (var i : start, end) { body }` →
//   `for i = start, (end - 1) do` (half-open [start, end)).
//
// Critical emission rules:
//   - The Logia `var` keyword and the colon are deliberately NOT
//     emitted — Lua's `for` doesn't use `var`; the counter is
//     implicitly declared by the `for` keyword itself.
//   - R5.0 short form: counter starts at 1 (hardcoded) and runs to
//     `bound` inclusive. No step argument is emitted.
//   - R5.0.1 range form: counter starts at `start` and runs to
//     `end - 1` inclusive (so the half-open `[start, end)` is
//     represented using Lua's inclusive numeric-for). The `end - 1`
//     is emitted as a parenthesized expression to avoid precedence
//     surprises with arithmetic in the bound (e.g. `end = n*2`
//     emits `for i = 0, (n * 2 - 1) do`).
//   - `bound` / `start` / `end` are emitted via emitExpr, so any
//     Logia expression reducing to a number is accepted (literal,
//     identifier, function call, arithmetic).
//   - Lua's `for i = a, b do ... end` already provides the lexical
//     scope for `i` (loop-local); no codegen-side scope marker is
//     required.
//
// Edge cases:
//   - By R5.2-C (2026-07-14) the analyzer guarantees the bound
//     statically reduces to int, so all numeric-for coercion is
//     now impossible at runtime.
//   - `bound == 0` / `bound < 1` is still legal (Lua skips the body).
//   - `start >= end` (i.e. `start > end - 1`) is still legal (Lua
//     skips the body).
//   - Non-integer bounds are now rejected at compile time by
//     SemanticAnalyzer::validateForBound (ErrorCode::TypeMismatch).
void LuaCodegen::emitForStmt(const ForStmt& stmt)
{
    // R5.2-B (2026-07-14): hoist top-level LabelDeclStmts out of
    // the for-body to AFTER the `for` block. See emitWhileStmt
    // for the rationale.
    indent();
    _out += "for ";
    _out += stmt.counterName;
    _out += " = ";
    if (stmt.start) {
        // R5.0.1 range form: emit `start, (end - 1)`.
        _out += emitExpr(*stmt.start);
        _out += ", (";
        _out += emitExpr(*stmt.bound);
        _out += ") - 1";
    } else {
        // R5.0 short form: emit `1, bound`.
        _out += "1, ";
        _out += emitExpr(*stmt.bound);
    }
    _out += " do\n";

    ++_indent;
    emitBlockSkipLabels(stmt.body);
    --_indent;

    indent();
    _out += "end\n";
    hoistLabelsFromBody(stmt.body);
}

// R5.1 (2026-07-13): `break;` → Lua `break`.
// R5.2-B (2026-07-14): `break :L` → `goto L`. Lua 5.2+ supports
// `goto` natively; this is the only way to exit an outer loop
// from a nested loop body. The parser's loopDepth gate +
// analyzer's label-visibility check together guarantee the
// label exists at codegen time.
void LuaCodegen::emitBreakStmt(const BreakStmt& stmt)
{
    indent();
    if (stmt.label.empty()) {
        _out += "break\n";
    } else {
        _out += "goto ";
        _out += stmt.label;
        _out += "\n";
    }
}

// R5.1 (2026-07-13): `continue;` → Lua `continue`.
// R5.2-B (2026-07-14): same optional `:LABEL` extension as break.
void LuaCodegen::emitContinueStmt(const ContinueStmt& stmt)
{
    indent();
    if (stmt.label.empty()) {
        _out += "continue\n";
    } else {
        _out += "goto ";
        _out += stmt.label;
        _out += "\n";
    }
}

// R5.2-A (2026-07-13): explicit `do ... end` shell. The body is
// emitted via the existing emitBlock helper (just iterates the
// StmtPtr vector). Indent is preserved by the surrounding
// LuaCodegen::indent() state — same convention as while/for
// bodies (see emitWhileStmt at L310, emitForStmt at L353).
//
// `do` is a pure block scope keyword in Lua (not a do-while loop);
// the parser already ensures the AST shape is correct.
void LuaCodegen::emitBlockStmt(const BlockStmt& stmt)
{
    indent();
    _out += "do\n";
    ++_indent;
    emitBlock(stmt.body);
    --_indent;
    indent();
    _out += "end\n";
}

// R5.2-B (2026-07-14): `::NAME::` shell. Lua 5.2+ supports label
// declarations natively. Same indent convention as `do/end` (the
// label sits at the same indent as the surrounding statement).
void LuaCodegen::emitLabelDeclStmt(const LabelDeclStmt& stmt)
{
    indent();
    _out += "::";
    _out += stmt.name;
    _out += "::\n";
}

void LuaCodegen::emitReturnStmt(const ReturnStmt& stmt)
{
    indent();
    _out += "return";
    if (stmt.value) {
        _out += " ";
        _out += emitExpr(*stmt.value);
    }
    _out += "\n";
}

void LuaCodegen::emitExprStmt(const ExprStmt& stmt)
{
    if (!stmt.expr) {
        return;
    }

    if (auto* bin = dynamic_cast<BinaryExpr*>(stmt.expr.get())) {
        TokenType op = bin->op.type;
        if (op == TokenType::Equal ||
            op == TokenType::PlusEqual || op == TokenType::MinusEqual ||
            op == TokenType::StarEqual || op == TokenType::SlashEqual) {

            // LG-05 / S3.3 — AYReflect-backed write for the
            // single-hop `self.<primitiveField>` pattern. Direct
            // assignment / compound assignment both lower to
            // explicit reflect reads + write so the runtime always
            // sees exactly one set call (no temp-around-lightuserdata
            // trap). Chained struct access (self.position.x += ...,
            // etc.) keeps the legacy compound-assign lowering which
            // is a runtime no-op for LG-05 scope.
            if (op == TokenType::Equal
                && isSingleHopSelfFieldExpr(*bin->left)) {
                std::string rhs = emitExpr(*bin->right);
                indent();
                _out += "ayt_reflect_set_field(self, \"";
                _out += _currentHostTypeName;
                _out += "\", \"";
                _out += singleHopSelfFieldName(*bin->left);
                _out += "\", ";
                _out += rhs;
                _out += ")\n";
                return;
            }
            if (isSingleHopSelfFieldExpr(*bin->left)
                && (op == TokenType::PlusEqual || op == TokenType::MinusEqual
                    || op == TokenType::StarEqual || op == TokenType::SlashEqual)) {
                // self.field <op>= rhs  →
                //   local __tmp = ayt_reflect_get_field(self, "T", "f") <op> rhs
                //   ayt_reflect_set_field(self, "T", "f", __tmp)
                std::string cur = "ayt_reflect_get_field(self, \"";
                cur += _currentHostTypeName;
                cur += "\", \"";
                cur += singleHopSelfFieldName(*bin->left);
                cur += "\")";
                std::string opName = tokenOpName(op);
                std::string rhs = emitExpr(*bin->right);
                std::string tmp = freshTmp("compound");
                indent();
                _out += "local ";
                _out += tmp;
                _out += " = ";
                _out += cur;
                _out += " ";
                _out += opName.substr(0, opName.size() - 1);  // strip trailing '='
                _out += " ";
                _out += rhs;
                _out += "\n";
                indent();
                _out += "ayt_reflect_set_field(self, \"";
                _out += _currentHostTypeName;
                _out += "\", \"";
                _out += singleHopSelfFieldName(*bin->left);
                _out += "\", ";
                _out += tmp;
                _out += ")\n";
                return;
            }

            // S3.11: multi-hop `self.<f1>.<f2>...<leaf> = <rhs>` and
            // `self.<...> <op>= <rhs>` lower to the chain reflect
            // helpers, parallel to the S3.10 single-hop blocks
            // above. The RHS itself can contain chain reads
            // (e.g. `self.position.y + self.jump_force * dt`),
            // which `emitExpr` recursively rewrites via Step 3 +
            // the existing single-hop MemberExpr rule.
            std::vector<std::string> chainNames;
            std::size_t hops = 0;
            if (!_currentHostTypeName.empty()
                && isSelfFieldChainExpr(*bin->left, chainNames, hops)) {
                if (op == TokenType::Equal) {
                    std::string rhs = emitExpr(*bin->right);
                    indent();
                    _out += "ayt_reflect_set_field_chain(self, \"";
                    _out += _currentHostTypeName;
                    _out += "\"";
                    for (const auto& n : chainNames) {
                        _out += ", \"";
                        _out += n;
                        _out += "\"";
                    }
                    _out += ", ";
                    _out += rhs;
                    _out += ")\n";
                } else {
                    // Compound assign on chain: get → op → set, all
                    // via the chain helpers.
                    std::string rhs = emitExpr(*bin->right);
                    std::string tmp = freshTmp("chain_compound");
                    std::string opName = tokenOpName(op);
                    // local __tmp = get_chain(self, "...", "f1", ..., "leaf") <op> rhs
                    indent();
                    _out += "local ";
                    _out += tmp;
                    _out += " = ayt_reflect_get_field_chain(self, \"";
                    _out += _currentHostTypeName;
                    _out += "\"";
                    for (const auto& n : chainNames) {
                        _out += ", \"";
                        _out += n;
                        _out += "\"";
                    }
                    _out += ") ";
                    // strip trailing '=' from opName (e.g. "+=" -> "+")
                    _out += opName.substr(0, opName.size() - 1);
                    _out += " ";
                    _out += rhs;
                    _out += "\n";
                    // ayt_reflect_set_field_chain(self, "...", "f1", ..., "leaf", __tmp)
                    indent();
                    _out += "ayt_reflect_set_field_chain(self, \"";
                    _out += _currentHostTypeName;
                    _out += "\"";
                    for (const auto& n : chainNames) {
                        _out += ", \"";
                        _out += n;
                        _out += "\"";
                    }
                    _out += ", ";
                    _out += tmp;
                    _out += ")\n";
                }
                return;
            }

            std::string rhs;
            if (op == TokenType::Equal) {
                rhs = emitExpr(*bin->right);
            } else {
                rhs = emitCompoundRhs(*bin->left, tokenOpName(op), *bin->right);
            }
            std::string target = emitAssignmentTarget(*bin->left);
            indent();
            _out += target;
            _out += " = ";
            _out += rhs;
            _out += "\n";
            return;
        }
    }

    indent();
    _out += emitExpr(*stmt.expr);
    _out += "\n";
}

// ============================================================
// Expressions
// ============================================================

std::string LuaCodegen::emitExpr(const Expr& expr)
{
    if (auto* b = dynamic_cast<const BinaryExpr*>(&expr)) {
        std::string l = emitExpr(*b->left);
        std::string r = emitExpr(*b->right);
        std::string out;
        out.reserve(l.size() + r.size() + 4);
        out += "(";
        out += l;
        out += " ";
        out += tokenOpName(b->op.type);
        out += " ";
        out += r;
        out += ")";
        return out;
    }
    if (auto* u = dynamic_cast<const UnaryExpr*>(&expr)) {
        std::string inner = emitExpr(*u->operand);
        std::string out;
        if (u->op.type == TokenType::Minus) {
            out += "(-";
            out += inner;
            out += ")";
        } else if (u->op.type == TokenType::Bang) {
            out += "(not ";
            out += inner;
            out += ")";
        } else {
            errorAt(u->op, "Unsupported unary operator");
            return "nil";
        }
        return out;
    }
    if (auto* c = dynamic_cast<const CallExpr*>(&expr)) {
        // S3.12 (track R2 §5.7.4): `self.method(args)` rewrites to
        // `ayt_reflect_call_method(self, "<Type>", "<method>", args...)`.
        // The analyzer stamps CallExpr::resolvedMethod only when the
        // callee is a MemberExpr on self AND the method exists on the
        // host type's reflect registry; otherwise the analyzer leaves
        // resolvedMethod=null and codegen falls back to bare Lua
        // dispatch (which still works for non-reflected method names
        // — they just won't actually invoke the C++ method).
        if (c->resolvedMethod != nullptr
            && c->resolvedMethodOwnerName != nullptr) {
            std::string out = "ayt_reflect_call_method(self, \"";
            out += c->resolvedMethodOwnerName;
            out += "\", \"";
            out += c->resolvedMethod->getName();
            out += "\"";
            for (const auto& a : c->args) {
                out += ", ";
                out += emitExpr(*a);
            }
            out += ")";
            return out;
        }
        std::string callee = emitExpr(*c->callee);
        std::string out;
        out += callee;
        out += "(";
        bool first = true;
        for (const auto& a : c->args) {
            if (!first) out += ", ";
            out += emitExpr(*a);
            first = false;
        }
        out += ")";
        return out;
    }
    if (auto* m = dynamic_cast<const MemberExpr*>(&expr)) {
        // S3.11 (LG-05 extended): multi-hop `self.<f1>.<f2>...<leaf>`
        // rewrites to `ayt_reflect_get_field_chain(self, "<Host>",
        // "<f1>", ..., "<leaf>")`. Probe before the single-hop gate
        // because the chain probe is more restrictive (>=2 hops,
        // every node resolvedField-stamped, leaf primitive) — single-
        // hop stays on the S3.10 path below.
        std::vector<std::string> chainNames;
        std::size_t hops = 0;
        if (!_currentHostTypeName.empty()
            && isSelfFieldChainExpr(*m, chainNames, hops)) {
            std::string out;
            out += "ayt_reflect_get_field_chain(self, \"";
            out += _currentHostTypeName;
            out += "\"";
            for (const auto& n : chainNames) {
                out += ", \"";
                out += n;
                out += "\"";
            }
            out += ")";
            return out;
        }
        // LG-05 / S3.3 — AYReflect-backed read: single-hop
        // `self.<primitiveField>` rewrites to the bridge's
        // reflect call. The `resolvedField` stamp comes from
        // SemanticAnalyzer; we additionally require the leaf type
        // to have no fields of its own (primitives like int/float/
        // bool). Struct members are out of S3.3 scope — kept as
        // bare Lua member access which becomes a runtime no-op
        // on the lightuserdata (matches S2.5 behavior).
        if (auto* objId = dynamic_cast<const IdentifierExpr*>(m->object.get())) {
            if (objId->name == "self"
                && !_currentHostTypeName.empty()
                && m->resolvedField != nullptr
                && m->resolvedType != nullptr
                && m->resolvedType->getFieldCount() == 0) {
                std::string out;
                out += "ayt_reflect_get_field(self, \"";
                out += _currentHostTypeName;
                out += "\", \"";
                out += m->member;
                out += "\")";
                return out;
            }
        }
        std::string obj = emitExpr(*m->object);
        std::string out;
        out += obj;
        out += ".";
        out += m->member;
        return out;
    }
    if (auto* i = dynamic_cast<const IndexExpr*>(&expr)) {
        std::string obj = emitExpr(*i->object);
        std::string idx = emitExpr(*i->index);
        std::string out;
        out += obj;
        out += "[";
        out += idx;
        out += "]";
        return out;
    }
    if (auto* id = dynamic_cast<const IdentifierExpr*>(&expr)) {
        return id->name;
    }
    if (auto* lit = dynamic_cast<const LiteralExpr*>(&expr)) {
        if (std::holds_alternative<bool>(lit->value)) {
            return std::get<bool>(lit->value) ? "true" : "false";
        }
        if (std::holds_alternative<int>(lit->value)) {
            return std::to_string(std::get<int>(lit->value));
        }
        if (std::holds_alternative<float>(lit->value)) {
            std::ostringstream oss;
            oss << std::get<float>(lit->value);
            return oss.str();
        }
        if (std::holds_alternative<std::string>(lit->value)) {
            return escapeString(std::get<std::string>(lit->value));
        }
        return "nil";
    }
    if (auto* t = dynamic_cast<const TableExpr*>(&expr)) {
        // S3.12+R3: emit `{k1=v1, k2=v2, ...}` where each `ki`
        // is a bareword identifier. Lua's table-constructor record
        // syntax `name=value` requires the key to be an identifier
        // (no quotes). The bridge reads each key with lua_getfield
        // after the table is on the stack; lua_getfield works on
        // both quoted-string and bareword table keys.
        std::string out = "{";
        for (size_t i = 0; i < t->entries.size(); ++i) {
            if (i > 0) out += ", ";
            const auto& e = t->entries[i];
            if (e.key) {
                // Identifier key — emit as bareword (no quotes).
                std::string keyName;
                if (auto* id = dynamic_cast<const IdentifierExpr*>(e.key.get())) {
                    keyName = id->name;
                } else {
                    // R3.0 only supports identifier keys; otherwise
                    // emit as `[expr] = value` syntax (Lua generic
                    // table constructor).
                    out += "[";
                    out += emitExpr(*e.key);
                    out += "] = ";
                    out += emitExpr(*e.value);
                    continue;
                }
                out += keyName;
                out += " = ";
            }
            out += emitExpr(*e.value);
        }
        out += "}";
        return out;
    }
    errorAt(Token{}, "Unsupported expression in codegen");
    return "nil";
}

// ============================================================
// Compound assignment lowering
//
// `transform.position.y += jump_force * dt` lowers to:
//   local __tmp_0 = transform.position
//   __tmp_0.y = __tmp_0.y + (jump_force * dt)
//
// emitAssignmentTarget() emits the prefix-statement fragment that creates
// the temporary and returns the Lua expression to use as the LHS.
// ============================================================

namespace {

bool collectMemberChain(const Expr& e, std::vector<std::string>& members)
{
    if (auto* m = dynamic_cast<const MemberExpr*>(&e)) {
        members.push_back(m->member);
        return collectMemberChain(*m->object, members);
    }
    return !members.empty();
}

} // namespace

std::string LuaCodegen::emitAssignmentTarget(const Expr& target)
{
    std::vector<std::string> members;
    if (!collectMemberChain(target, members)) {
        return emitExpr(target);
    }
    std::vector<std::string> rev(members.rbegin(), members.rend());
    std::string tmpName = freshTmp("lhs");
    indent();
    _out += "local ";
    _out += tmpName;
    _out += " = ";
    if (auto* m = dynamic_cast<const MemberExpr*>(&target)) {
        _out += emitExpr(*m->object);
        for (size_t i = 1; i + 1 < rev.size(); ++i) {
            _out += ".";
            _out += rev[i];
        }
    } else {
        _out += "nil";
    }
    _out += "\n";

    std::string out;
    out += tmpName;
    out += ".";
    out += rev.back();
    return out;
}

// ============================================================
// LG-05 / S3.3 helpers
// ------------------------------------------------------------
// isSingleHopSelfFieldExpr / singleHopSelfFieldName probe the AST
// shape directly and never touch `_currentHostTypeName`, so they
// behave identically whether or not the script name resolved in
// AYReflect. The reflect-call rewrite in emitMemberExpr /
// emitExprStmt gates on `_currentHostTypeName` non-empty — here we
// just ask "is this a one-hop self.<primitiveField>?" and let the
// callers decide.
// ============================================================

bool LuaCodegen::isSingleHopSelfFieldExpr(const Expr& e)
{
    auto* m = dynamic_cast<const MemberExpr*>(&e);
    if (!m) return false;
    auto* objId = dynamic_cast<const IdentifierExpr*>(m->object.get());
    if (!objId || objId->name != "self") return false;
    if (m->resolvedField == nullptr) return false;
    if (m->resolvedType == nullptr) return false;
    // Primitive leaf only (int/float/bool/etc.). Chained struct
    // subfield access keeps the legacy compound-assign lowering,
    // which is a runtime no-op for S3.3 (out of scope).
    return m->resolvedType->getFieldCount() == 0;
}

std::string LuaCodegen::singleHopSelfFieldName(const Expr& e)
{
    auto* m = dynamic_cast<const MemberExpr*>(&e);
    return m ? m->member : std::string();
}

// S3.11: probe a multi-hop `self.<f1>.<f2>...<leaf>` chain. Returns
// true and fills `fieldNames` (root→leaf order) when every MemberExpr
// in the chain has `resolvedField != nullptr` (analyzer stamped the
// AYReflect IFieldInfo for each hop) and the leaf's resolvedType is
// a primitive (getFieldCount() == 0). `hopCount >= 2` gate keeps
// `self.field` (single hop) on the existing S3.10 path; otherwise
// every chain would be re-routed to the new helpers and S3.10 tests
// would see different codegen output.
bool LuaCodegen::isSelfFieldChainExpr(const Expr& e,
                                     std::vector<std::string>& fieldNames,
                                     std::size_t& hopCount)
{
    fieldNames.clear();
    hopCount = 0;

    // Walk the chain from the leaf inward; collect names in reverse.
    std::vector<std::string> reversed;
    const Expr* cur = &e;
    while (auto* m = dynamic_cast<const MemberExpr*>(cur)) {
        if (m->resolvedField == nullptr) {
            return false;  // analyzer couldn't resolve this hop
        }
        reversed.push_back(m->member);
        ++hopCount;
        cur = m->object.get();
    }

    // The root must be the `self` identifier (NOT another member expr,
    // NOT an arbitrary expression — chain must be `self.*`).
    auto* rootId = dynamic_cast<const IdentifierExpr*>(cur);
    if (!rootId || rootId->name != "self") {
        return false;
    }

    // Require primitive leaf so the runtime helper can call
    // pushFieldPrimitive on the final hop.
    auto* leafM = dynamic_cast<const MemberExpr*>(&e);
    if (!leafM || leafM->resolvedType == nullptr
        || leafM->resolvedType->getFieldCount() != 0) {
        return false;
    }

    if (hopCount < 2) {
        return false;  // single-hop stays on the S3.10 path
    }

    // Reverse to root→leaf order.
    fieldNames.assign(reversed.rbegin(), reversed.rend());
    return true;
}

std::string LuaCodegen::emitCompoundRhs(const Expr& target,
                                       const std::string& op,
                                       const Expr& rhs)
{
    std::vector<std::string> members;
    std::string lhsStr;
    if (collectMemberChain(target, members)) {
        std::vector<std::string> rev(members.rbegin(), members.rend());
        if (auto* m = dynamic_cast<const MemberExpr*>(&target)) {
            lhsStr = emitExpr(*m->object);
            for (size_t i = 1; i < rev.size(); ++i) {
                lhsStr += ".";
                lhsStr += rev[i];
            }
        }
    } else {
        lhsStr = emitExpr(target);
    }
    std::string rhsStr = emitExpr(rhs);
    std::string out;
    out += lhsStr;
    out += " ";
    out += op;
    out += " ";
    out += rhsStr;
    return out;
}

std::string LuaCodegen::freshTmp(const std::string& hint)
{
    ++_tmpCounter;
    std::string name = "__tmp_";
    if (!hint.empty()) {
        name += hint;
        name += "_";
    }
    name += std::to_string(_tmpCounter);
    return name;
}

// ============================================================
// Helpers
// ============================================================

void LuaCodegen::line(const std::string& s)
{
    indent();
    _out += s;
    _out += "\n";
}

void LuaCodegen::indent()
{
    for (int i = 0; i < _indent; ++i) _out += "    ";
}

void LuaCodegen::dedent()
{
    if (_indent > 0) --_indent;
}

std::string LuaCodegen::escapeString(const std::string& s) const
{
    std::string out;
    out.reserve(s.size() + 2);
    out += '"';
    for (char c : s) {
        switch (c) {
        case '"':  out += "\\\""; break;
        case '\\': out += "\\\\"; break;
        case '\n': out += "\\n";  break;
        case '\r': out += "\\r";  break;
        case '\t': out += "\\t";  break;
        default:
            if (static_cast<unsigned char>(c) < 0x20) {
                char buf[8];
                std::snprintf(buf, sizeof(buf), "\\x%02X", static_cast<unsigned char>(c));
                out += buf;
            } else {
                out += c;
            }
        }
    }
    out += '"';
    return out;
}

void LuaCodegen::errorAt(const Token& tok, const std::string& message)
{
    CompilerError err;
    err.code = ErrorCode::InvalidStatement;
    err.message = message;
    err.line = tok.line;
    err.column = tok.column;
    _errors.push_back(err);
}

} // namespace ayt::script::logia